### ISSUE TITLE
[WARNING]: Node-ipc has been sabotaged.

### ISSUE THREAD

**Issue by ACodingGenie** [fgl27/SmartTwitchTV#104]
**Describe what you need.**
Not sure if the package is used within this application but node-ipc was sabotaged by the maintainer as a way to “protest” against the ongoing war. Please do not update as it deletes all files on system once executed. I saw node as one of the tags and thought I'd alert you. Thank you.

URL: https://github.com/RIAEvangelist/node-ipc

**Comment by fgl27** [comment]
Thank you.

That particularly module isn't used on this project.
