### ISSUE TITLE
Latency to broadcaster and buffer constantly decreasing

### ISSUE THREAD

**Issue by ntelas** [fgl27/SmartTwitchTV#105]
**Describe the bug**
While watching a stream with low latency mode off, "latency to broadcaster"  keeps decreasing. It reaches a point where it's only around 2.5 secs and buffers with the slightest internet speed fluctuation. It eventually reaches "low latency" mode by itself. Of course this doesn't let buffer to load as well, because there is no buffer to load.

**To Reproduce**
1: Open a stream and disable low latency mode.
2: Enable player status visibility always on.
3: Numbers speak for themselves.

**Expected behavior**
The latency should stay the same or increase in case of a major internet speed drop.
 
 **Device:**
 - SKYWORTH HY4415
 - Android 10

**Additional context**
My guess is that the video stream runs at a faster speed than should.

**Comment by fgl27** [comment]
this statement is wrong for live streams:
 
> The latency should stay the same or increase in case of a major internet speed drop.
 
This problem is that either your internet has an issue and can't load more content or the streamer has an issue and can provide more content to the server.
 
The app only shows what it can see, in this case it measures the time of the amount of content not yet played, or your device can' t load it or the server isn't receiving more content from the streamer.
 
In both cases the latency/buffer amount must decrease as the playback never stops.
 
get it?

**Comment by fgl27** [comment]
If the buffer is decreasing as the tile points, the latency will decrease in the case the app is not able to see more content on the server, so the value displayed is correct.

**Comment by ntelas** [comment]
I'm sorry, I never mentioned in how much time it takes for this to happen. This is happening in a duration of around 5 minutes. Every second, the latency to broadcaster is decreasing by few thaousandths of a second. This number is super approximate but should give you the idea of what I mean.

If it happened in sync with the time elapsed, I'd never report is as a problem because it is not(would mean the above you said earlier)

Maybe this changes your view on my issue.

**Comment by fgl27** [comment]
Yes I understood, maybe the playback is faster then what it should, as time goes we have a issue.

One thing that can do that is frame rate… What is the problematic stream frame rate and the frame rate of the device, on the settings of the device?

**Comment by ntelas** [comment]
The streams are 1080p60. HDMI output is set to 1080p at 60Hz. Just tested with another much faster connection as well. Same results.

**Comment by fgl27** [comment]
I did some test here and the issue is on how the latency value is calculated to be displayed.

Is just a display issue, it will not cause  the player to play faster or slow or cause rebuffer.

There is only one fix today that is use the player progress bar to set a time, when you do that the value will correct it self after 30s or so.

When this gets fix I let you know, as is a player issue and the player is from google I have to let them know.

**Comment by ntelas** [comment]
Thanks for digging further and finding the actual issue. I am observing that the "Buffer size" is always smaller than "latency to broadcaster". As a result,  even with a good connection the buffer will eventually get low enough that may cause some trouble.

Granted, with a very good connection, even with just 2.5 seconds of buffer it shouldn't have trouble. So it's not an issue many realize, unless they are at adsl speeds.

I tested the fix by selecting a point in the progress bar and it seems to work. It keeps both latency and buffer at a stable rate. Can this fix get implemented in a future release, as an automatic option? Maybe called "buffering fix for slow connections (will increase latency)".

Again, thanks for the support and time put into the app!

**Comment by fgl27** [comment]
I don't think this issue will cause a buffer issue as is a display issue, the value on the screen is wrong, if you disabled the lowlatency the buffer must be around 14 seconds regardless of what display unless you have an internet issue, preventing the player from load content.

As this is an display issue I will not make any workaround, as only affect those that disable low latency with comes enable by default.

**Comment by fgl27** [comment]
V 331 (3.0.331) fix this issue, will be available to update on play store soon.

thanks for the help @ntelas :+1:

**Comment by ntelas** [comment]
Thank you for the fix!

**Comment by ntelas** [comment]
I installed the update and noticed something. Now the latency is increasing automatically (reduces playback speed), until it reaches a certain point. 

Tested both on slow connection(<7MBPS) and fast connection(>50MBPS). 
On the slow one it increased by almost 10 seconds in just 5 minutes(looks like it stabilized around 30 seconds delay). 
On the fast connection this doesn't appear to happen. It is stable from the start.

Is this the intented behavior you want or should be fixed as well?

**Comment by fgl27** [comment]
I will check that... Seems to be a feature but not something the app controls, it happens internally on the player.

I didn't manage to test are you sure only happens if the internet is show?

If there is another way to reproduce it let need know

**Comment by ntelas** [comment]
It doesn't happen now. I tried to replicate it manually by adjusting the internet speed, but without success. So connection speed most likely is not the trigger.
However, **it did it when it had to re-buffer** because of a sudden internet speed drop.

Here is what it might be:
https://exoplayer.dev/live-streaming.html#:~:text=targetLiveOffsetIncrementOnRebufferMs

**Comment by Supernoodles1990** [comment]
Unsure if i'm having the same issue on my GoogleTV (Chromecast) every stream i load up is perfect dropped / skipped frames or buffering latency to broadcaster is only like 1/2 seconds but after about 5 mins its up as high 10 seconds i only noticed the issue because the stream ended up being behind the chat quite badly.

My connection is 80 down 20 up if this isn't related then i'll make my own thread :) ty in advance and love everything that you do

**Comment by Kline-** [comment]
> Unsure if i'm having the same issue on my GoogleTV (Chromecast) every stream i load up is perfect dropped / skipped frames or buffering latency to broadcaster is only like 1/2 seconds but after about 5 mins its up as high 20 seconds i only noticed the issue because the stream ended up being behind the chat quite badly.

This is the issue I'm having as well. I'm not sure if it's related to the other ExoPlayer issue discussed above or if this is something that should be its own issue.

Looking at video stats my latency to broadcaster seems to increase by about 0.02 seconds every second with 0 skipped/dropped frames. This continues until latency is about 20-30 seconds and I assume the buffer is full, then the stream dumps the buffer and skips forward to live content similar to if I had done so manually.

These images were taken immediately after opening the stream and then about 5 minutes later on a ShieldTV 2015 with a 200/20 internet connection.

![image](https://user-images.githubusercontent.com/1126350/164214917-2b1e7325-0ff3-467d-a562-684cdb10f547.png)
![image](https://user-images.githubusercontent.com/1126350/164214987-ed526b7b-8ae4-4b22-aac7-98ff6fb044d3.png)

**Comment by fgl27** [comment]
I'll make a new change on the weekend and yous guys can test.

thanks

**Comment by Js41637** [comment]
Hey. Just wondering if any progress has been made on this? I've noticed the same issue where watching a stream. The latency or delay slowly increases. I wouldn't even notice apart from the fact it gets quite obvious that the chat is out of sync with what is happening on screen and then checking the progress bar it shows it's considerably behind.

**Comment by DooMMasteR** [comment]
Yeah I also noticed it, maybe the recent changes fix it? At least yesterday it was still an issue for me, so maybe not? but I cannot be sure, have to check the version I am running later....

**Comment by ntelas** [comment]
Recent changes limited the player from going faster than it should, fixing the issue mentioned in this thread. 

This however, in some cases(like buffering), it creates the opposite effect. Player starts slowing down, constantly increasing the buffer and latency to broadcaster in result. (It's a mechanism that was not properly implemented by the app)

The developer has looked into it and planning to fix it very soon.

**Comment by DooMMasteR** [comment]
Well for me the issue is mitigated by one time manually reducing the buffer after starting a stream.
Once I have fast forwarded as far as possible the buffer does not increase abnormally again.  

This is obviously not a fix, but a good workaround. (Mi Box 3 the old one, non S).

**Comment by LordBoos** [comment]
Is there any update to this issue? I have 1 Gbps internet speed and I have a problem with latency increasing over time at a pretty fast pace. After a few minut of watching I got 90-100 seconds of delay. I have to reset the player pretty often. It is really annoying. I tried to fix the issue myself but I can't get the self-build version - even with unchanged files - to start on my TV. Release unsigned APK just refuses to install and debug version wont start and instantly closes unfortunately. I had to temporarily move to the official Twitch app.

**Comment by Kline-** [comment]
Have you tried turning off low latency mode entirely yet? That has been a
good workaround for me that keeps the buffer fixed around 15 seconds and
perfectly stable.

The author mentioned he hasn't had time to work on this yet due to real
life complications.

**Comment by LordBoos** [comment]
Thing is I mainly watch small streamers that interact with chat in real time and even 15s delay seems too much for this kind of interaction. That's why I loved the lowest latency mode which was stable for me in the past and delay was stable at ~2 seconds, which was great.

I hope that fgl27's real life complications will be resolved soon and wish him only the best!

**Comment by DooMMasteR** [comment]
@LordBoos try my fix, manually fast forward the buffer once it has built up, it then stays at a low level.

**Comment by fgl27** [comment]
Te above must fix the issue, a new app was released test let me know.

**Comment by Supernoodles1990** [comment]
Issue seems to be fixed for me haven't seen my latency to broadcaster go over 4 seconds on low latency :)

**Comment by Kline-** [comment]
Looking good here as well, enabled low latency mode and it has been stable
around 3s for over an hour 👍
