### ISSUE TITLE
Hold time on left key is too short

### ISSUE THREAD

**Issue by patriq** [fgl27/SmartTwitchTV#11]
**Describe the bug**
Often times I am trying to navigate the app using the arrow keys, but often times when I press the left key, instead of going to the left it opens a menu that is only supposed to open when I long press the left key. This started happen like a week or two ago, although I am not sure on the timing. 

**To Reproduce**
1. Go to the Gamessection
2. Navigate all the way to the right (to the 4th game)
3. Try to navigate left (to the 1st game)
4. The Thumbnail Options menu pops up

**Expected behavior**
It should allow me to navigate to the left the same way I navigate to the right. If I press down the right button it keeps scrolling to the right.
 
 **Device:**
 - TV Manufacture Device: Philips 65OLED804
 - Os version: Android 9

**Additional context**
I am in the latest version as of today in Google Play.

**Comment by patriq** [comment]
Looking at the code I think that this is the problem: https://github.com/fgl27/SmartTwitchTV/blob/master/app/specific/Screens.js#L7

250ms is way to little time. Consider increasing this to something like 500ms.

**Comment by fgl27** [comment]
No, I can make it configurable

**Comment by patriq** [comment]
That also works. But make it 500ms be default. I don't think 250ms is a good "press" timeout.

**Comment by fgl27** [comment]
No on all my devices 250 is perfect I never ever have that issue, you are only checking yours device that I assume has a problem, I have tested on many devices included very old phones and that issue is not a thing.

**Comment by patriq** [comment]
I am suggesting 500ms since it is the Android default when long pressing as you can see here: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/ViewConfiguration.java#68

Do make it configurable then 👍

**Comment by fgl27** [comment]
The feature has be added. hold key return if the app is open so it closes, when open again the feature will be there.

Settings "Animations, Style and related"

**Comment by patriq** [comment]
I see it, and set it to 500ms. It solves my problem but introduces another.

The UI seems less responsive. If I press left, the selection only seems to move left 500ms after I release the key, when it should be done immediately like when I use the right key.

**Comment by patriq** [comment]
It does solve the issue, but using left is slower than using right button. Seems like instead of moving when the key is up it waits for the 500ms to move. Anyway, the original issue is fixed so I will be closing this.

**Comment by fgl27** [comment]
I don't why maybe your device has a issue
open the app page using this

https://fgl27.github.io/SmartTwitchTV/release/index.min.html

set for yours self the delay time doesn't matter set it to 2000 the left and right key have the same behavior in relation to time, the only diference is that the right action happens on click down the left on click up (release the key).

**Comment by fgl27** [comment]
You also use the page to test that a very small value doesn't prevent the key from work. Only on yours device does.

**Comment by patriq** [comment]
You are right! I wonder why! Anyway thanks for providing the option! 😄

**Comment by fgl27** [comment]
The only thing I'm aware that can lag a action of this app is accessibility services, that is why I have added a warning about that, accessibility services affect apps and devices differently on this app is lag on actions as keys press.

Settings warnings you can see it. if you don't have a accessibility service enable I don't know what can be, maybe a app that runs on background or something like that.
