### ISSUE TITLE
The ability to watch vods is gone?

### ISSUE THREAD

**Issue by Fatcakes** [fgl27/SmartTwitchTV#111]
I'm guessing this has to do with restrictions on the new api. That being said, use twire on my phone which uses the api and I can watch vods.

**Comment by catska2jc** [comment]
Yeah vods and channels has not worked for me for a while either. Twire does work for vods for me but doesn't show chat replay. I hope this project gets updated one day for the new api.

**Comment by fgl27** [comment]
check here no span please I'm aware of issues.

https://github.com/fgl27/SmartTwitchTV/issues/94
