### ISSUE TITLE
Picture in picture mode not working

### ISSUE THREAD

**Issue by Ridelikepanda** [fgl27/SmartTwitchTV#115]
Picture in picture mode is not working. When I press up after having a stream selected, the other available streams will load. When I select a stream to enter PIP mode, the new stream will show in the upper left hand corner of the screen and the rest of the screen will be black. The audio of the original stream will be playing in the background. 

My TV is a TCL 55C725

Please see the attached photo below

![IMG20220628143352](https://user-images.githubusercontent.com/108323478/176109513-78605dd3-a300-423f-a1e2-75f00403b4d1.jpg)

**Comment by fgl27** [comment]
This is a device issue, you cab try to enable the bellow on settings see if helps.

![image](https://user-images.githubusercontent.com/13755892/176785957-46f3188c-1c7e-4b47-ae49-5d1357492cfb.png)

**Comment by Ridelikepanda** [comment]
It worked, thank you!
