### ISSUE TITLE
SmartTwitchTV randomly skips frames which sometimes leads lags

### ISSUE THREAD

**Issue by towlie** [fgl27/SmartTwitchTV#118]
**Describe the bug**
SmartTwitchTV randomly skips frames and sometimes (not always) you can also see the buffering circle for a few milliseconds.

**To Reproduce**
1. Open a stream
2. Watch a stream until you see skipped frames or laggs

**Expected behavior**
The expected behavior is: no skipped frames or laggs while watching a stream. 

**Screenshots**
![about](https://user-images.githubusercontent.com/6986141/178379379-3cff2378-9304-4e6d-93a7-d72bbafc3ae2.jpg)

Stream start:
![MVIMG_20220712_013018](https://user-images.githubusercontent.com/6986141/178379962-a0c994d8-46f2-4f55-b912-cb12109dbb1d.jpg)

After 15 min of watching stream without doing anything (lowest latency mode):
![MVIMG_20220712_014522](https://user-images.githubusercontent.com/6986141/178380024-4fb7bc0c-5537-4ce8-8a43-cbf8c24c13fb.jpg)

Without low latency mode:
After 20 min of watching without doing anything
![MVIMG_20220712_032711](https://user-images.githubusercontent.com/6986141/178389013-4ac89136-d6e3-40ce-ab04-5d53c78c7e6b.jpg)
 
 **Device:**
Latest SmartTwitchTV Version
Chromecast with Google TV
Android 10 latest Firmware and the previous one

**Additional context**
I'm using a 100Mbit connection
I tried to disable low latency mode
Accessibility Service is disabled (was enabled once)

**Comment by fgl27** [comment]
50 frames in 20 min or in 72000 played frames is an issue for you?

Skipped frames can came from a minor device lag, a out of sync audio and video an internet hiccup.

Doesn't matter how good/fast yours internet is you can't control yours isp connection to a random twitch server.

That device is a low end device, 50 frames lost on that window of time on a low end device isn't a issue for me or something that I see as an app problem.

**Comment by towlie** [comment]
The issue is more that the stream starts to hang randomly for a short moment. The skipped frames are just the indicator.
The reason why I think this is an app issue is because I never noticed those on other streaming apps. ( even on the original Twitch app )
The connection to the twitch server shouldn't be the issue because it also happens with a 15s buffer (see picture 3) which never gets empty.

So you think this could be related to my device? Then I will try to figure out what could be the cause.
I guess I can live with those small lags. I just thought it's worth a report.
Thanks for the app!

**Comment by fgl27** [comment]
You clear have a overlay on the screen to show up/down speeds, isn't that a Accessibility Service?

Accessibility Service will cause a lot of lag, I would start disabling that overlay.

If you can share a way to reproduce the problem I can't help, on all of my devices that doesn't happens.

Maybe a factory reset solves, Android devices are know to have random odd bugs.

**Comment by towlie** [comment]
The overlay is a network monitor which I disabled after reporting the issue. (It works without Accessibility Service and only needs draw permissions) At first I though it helped but it did not. 
I also saw that those drops/lags happen on VODs.

I think I will try to reset the whole device. I remember reading something about lags on corresponding chromecast subreddits a while ago.
