### ISSUE TITLE
"Player unable to play due player error. Error code:4001

### ISSUE THREAD

**Issue by Bricio92** [fgl27/SmartTwitchTV#119]
Only this channel (Ciccio_Merrino) report this error to play. 
It's possible to fix it?

Fire TV Stick Lite
Apk: last version

![20220722_143914.jpg](https://user-images.githubusercontent.com/91467148/180441297-499a9027-e622-4256-9b4a-869a2fd382b4.jpg)

**Comment by fgl27** [comment]
Why are you bordering again? 
I already try to help you, but you don't care https://github.com/fgl27/SmartTwitchTV/issues/110
