### ISSUE TITLE
Getting ads on every channel even though I have turbo, just started with new update 

### ISSUE THREAD

**Issue by atag012** [fgl27/SmartTwitchTV#121]
Ads are playing on all channels for no reason.

**To Reproduce**
1. Play any stream, ads play 

**Expected behavior**
no ads 
 
 **Device:**
 - nvidia shield

**Comment by zazomazzo** [comment]
Same here, also on Nvidia Shield.

**Comment by atag012** [comment]
Going into settings. Then proxy, and Turning one on, the ads are gone but maybe just a temp solution

**Comment by Supernoodles1990** [comment]
Doesn't matter which blocker I use I'm getting ads :/ before this change there was never any in any channels subscribed or not

**Comment by fgl27** [comment]
see #120 close for the same reason
