### ISSUE TITLE
Sub only VODs

### ISSUE THREAD

**Issue by JSKALTEN** [fgl27/SmartTwitchTV#122]
Hi, thanks for your hard work and pushing out many updates over the last month. It’s a great app!

I noticed that when trying to view one of my channels, who has sub only VODs, that it would give an error (can’t play/forbidden) when trying to play a VOD, and with the current version it gives the error of ‘video/clip failed to load’ or ‘unable to get video link’. Not sure if you are aware of this issue.

Also, I’m not sure if this request has been implemented yet or in the process of, but auto-collecting channel points would be amazing if possible. Thanks!

**Comment by fgl27** [comment]
on the future may be possible to show sub only content, right now is a twitch limitation for thirdly party apps.

auto-collecting channel points is something that depends on first party tokens, something this app can't get as is a thirdly party apps.

the only workaround is if you use something else to collect (yours phone or computer using some app/script), but that is hard to find as twitch sees that as a violation and may ban those  who use or share it, I particularly don't use channel points so I can't help on how to manage to get them like that.

**Comment by fgl27** [comment]
The above fix the message displayed on the screen, thanks.
