### ISSUE TITLE
'VOD unreachable' when selecting any VOD

### ISSUE THREAD

**Issue by Vlangusy** [fgl27/SmartTwitchTV#123]
**Describe the bug**
When I select any VOD I get a message "(channel name) Preview failed to download: VOD unreachable, this VOD may have been deleted" and when I try to play it there is a message "Unable to get video link" and the app acts as if the video has ended. I can't play any VOD.

**To Reproduce**
- go to any channel
- open vods page
- select any vod and try to play it

**Expected behavior**
Play any vod after selecting and clicking it.

**Additional info**
Vods nor highlights don't work. Clips do work though.

**Comment by fgl27** [comment]
I have testes and the app is just fine, can't reproduce the problem. 

I advise to reboot yours device, if that doesn't work check yours network setting or something related, try to uninstall the app reinstall maybe is a random bug.

**Comment by Vlangusy** [comment]
![IMG_20220903_113249](https://user-images.githubusercontent.com/95291637/188264914-8ae5cd69-8c0c-4802-8615-79f130673428.jpg)
I have even reinstalled TV just now (reinstalled Android and set up the TV as if it was fresh) and it's still the same issue. I have a Phillips TV from the year 2015 or sth with Android 5.1.1. I don't now what network issue that could be, livestreams play just fine.

**Comment by fgl27** [comment]
Test a different device and network for you to see that works after try to find what causes a issue on the TV.

You can download the APK from here

https://github.com/fgl27/SmartTwitchTV/releases

Install on any device.

**Comment by Vlangusy** [comment]
Works in the same network on my phone. On the TV still doesn't work when I made a hotspot on the phone while using a data plan for the Internet connection.

**Comment by fgl27** [comment]
Yours TV has a unknow issue, probably the old android causing a random issue.

Technically a Live and a Vod work the same way regarding starting the playback (the diff one is live the other isn't), doesn't make sense this issue affecting only Vods

This isn't something I can fix as I can't reproduce, if you manage to find a solution let me know.

**Comment by fgl27** [comment]
Bellow attached a test apk, that will show on the screen more info related to the error causing this problem

[app-debug.zip](https://github.com/fgl27/SmartTwitchTV/files/9497701/app-debug.zip)

To test...

1. unzip
2. install the apk
3. open a vod screen and use the preview to cause the error
4. take a picture and share here

The test app has a yellow icon so you can differentiate

**Comment by Vlangusy** [comment]
![IMG_20220906_165435~3](https://user-images.githubusercontent.com/95291637/188668553-3f730ca8-0308-429d-ac92-0d22072d390f.jpg)
this "Status: 0 responseText:" on top of the screen is the only message that shows, either while being logged in or not. When I click on a vod it is still just "Unable to get video link".

**Comment by fgl27** [comment]
OK that didn't helped, lets try the bellow same test.

[app-debug.zip](https://github.com/fgl27/SmartTwitchTV/files/9498520/app-debug.zip)

The app is crashing on the APK side, if this doesn't show the proper error I will need you to get the Android Log next.

**Comment by fgl27** [comment]
[app-debug.zip](https://github.com/fgl27/SmartTwitchTV/files/9498562/app-debug.zip)

if you downloaded from before post try again with this now, if not just test this as explain before

**Comment by Vlangusy** [comment]
OK, so I still don't see any debugging output on-screen, but now with this version of the app I can watch VODs without problems.
I might have not mentioned that I've been using the app for months or years already and the issue was only very recent.

**Comment by fgl27** [comment]
BTW test on main app version and let me know if all OK.

**Comment by Vlangusy** [comment]
Yep, now everything works on the main app, the one straight from the Play Store. Thank you too :)
