### ISSUE TITLE
App doesn't open anymore after update.

### ISSUE THREAD

**Issue by casualkitten1** [fgl27/SmartTwitchTV#124]
**Describe the bug**
The app doesn't open anymore after updating to the latest update. 

**To Reproduce**
Update
Try to launch the app
**Expected behavior**
The app to launch (lol)

 
 **Device:**
strong leap-s1

**Additional context**
The app is great and worked fine until the last update. Sadly I can't open it. It loads for few seconds and goes back to whichever tab I was on. 

Thanks for your work.

**Comment by fgl27** [comment]
This is a very minor update, seems you have a random install bug.

Have you tried to uninstall reinstall?

**Comment by casualkitten1** [comment]
> This is a very minor update, seems you have a random install bug.
> 
> 
> 
> Have you tried to uninstall reinstall?
> 
> 
> 
> 

I'll try and let you know ! :-)

**Comment by casualkitten1** [comment]
Hey ! I reinstalled the app through the app store, it found my last settings automatically, and everything works now. 


Thanks a lot!
