### ISSUE TITLE
vod chat not working

### ISSUE THREAD

**Issue by henriklb** [fgl27/SmartTwitchTV#126]
**Describe the bug**
vod chat not working

**To Reproduce**
watch vod, open chat, chat window is blank

**Expected behavior**
a replay of live chat (vod)

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - shield tube 2019 latest update

**Additional context**

**Comment by itends** [comment]
Same problem here, also on shield pro 2019

**Comment by fgl27** [comment]
That will be fixed on next app update.

**Comment by fgl27** [comment]
The app received a update to fix the issue. If anything else open a new issue.

thanks you
