### ISSUE TITLE
Feature Request - Save individual channel volume settings

### ISSUE THREAD

**Issue by ddmagnas** [fgl27/SmartTwitchTV#127]
The app already allows users to change the volume of an individual channel.  This request is to allow those per-channel volume settings to be saved and applied when the user next visits the channel, even if the app is closed.

Current state: User opens Channel A, goes to volume settings, lowers volume to 40%.  User leaves Channel A to watch Channel B, or closes the app.  When user next comes back to Channel A (or watches the preview thumbnail), the volume setting for that channel has gone back to the default 100%.

Future state: User opens Channel A, goes to volume settings, lowers volume to 40%.  User leaves Channel A to watch Channel B, or closes the app.  When user next comes back to Channel A (or watches the preview thumbnail), the volume setting for that channel remains at 40%.

**Comment by fgl27** [comment]
Updated the app feature request list to included this.

https://github.com/fgl27/SmartTwitchTV/blob/master/apk/TODO.md
