### ISSUE TITLE
Ads constantly showing for turbo user

### ISSUE THREAD

**Issue by mmendivilg** [fgl27/SmartTwitchTV#128]
**Describe what you need.**
I don't know why I am getting ads even though I am a turbo user, Is there an reason why?
I am willing to pay a subscription to this app to be able to remove ads

**Additional context**
Turbo user with active subscrition to the channel in question, and I linked the account to the app successfuly

**Comment by fgl27** [comment]
Third party apps can't use user privilege, that includes sub or turbo privilege.

yours best option is use official twitch app or site.

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/172
