### ISSUE TITLE
app won't start after tv turned off on sony x900h

### ISSUE THREAD

**Issue by blomman00** [fgl27/SmartTwitchTV#131]
**Describe the bug**
after tv turned off for while, when starting the app it immediate closes withot any message, sometimes you see a twitch channel for a second. only way to make it start is to clear data, it will find the twitch user backup but settings is gone.

**To Reproduce**
turn off the tv on a sony bravia x900h europe using firmware 6.1874 and wait a while, turn on and start the app

**Expected behavior**
it should start without removing data

**Screenshots**
n/a
 
 **Device:**
 - sony bravia x900h europe firmware 6.1874
 - Os version: android tv 10

**Additional context**
really like your twitch client, would be nice if i could avoid this startup problem

**Comment by fgl27** [comment]
Very odd behavior, never heard of....

Let me see the about of the app...

Also try to share a bug report, but use this APK

https://github.com/fgl27/SmartTwitchTV/files/10490343/app-debug.zip

that is a zip so extract before installing, use FX file explorer or similar to extract and install.

Here how to bug report

https://developer.android.com/studio/debug/bug-report

**Comment by fgl27** [comment]
That app is a debug app, it has a different yellow color icon.

Gen the bug report after the app crash

**Comment by blomman00** [comment]
thanks for the quick response!
installed the debug version , but now a day later neither the real version or the debug version crash, before that i had a 4 day streak with crashes, have no idea what's going on here...
should i close this issue and reopen if it happens again?

**Comment by fgl27** [comment]
No let it open...

Maybe is a very particular settings you changed, or something else related to some system app that got updated and now no more issue, as the issue was outside the app.

anyway if happens share a bug report if not in a week or two I close this.
