### ISSUE TITLE
Stream language multi selections

### ISSUE THREAD

**Issue by Stephan-4711** [fgl27/SmartTwitchTV#132]
Hi, 

I really would appreciate it, if there would be a possibility to select more languages showed as streaming language in settings. 
For example I would like to see all german and English language streams

**Comment by fgl27** [comment]
No something supported by Twitch APIs.

**Comment by Stephan-4711** [comment]
So can set your own language, but not two different?
This isn't an setting just inside the app?
If so, is there a possibility to set the language while inside a game?

**Comment by fgl27** [comment]
Hold left gives you a menu, in witch you can change the lang

**Comment by fgl27** [comment]
Twitch API are mono language.

**Comment by fgl27** [comment]
There is also a option to change that from players controls, that is useful for in player content
