### ISSUE TITLE
Vod sub-only feature

### ISSUE THREAD

**Issue by Bricio92** [fgl27/SmartTwitchTV#135]
Could you may implement the function of watching vods for subs only in the future, as the desktop browser extension "TwitchNoSub" by besuper?

https://github.com/besuper/TwitchNoSub

Thank you so much

**Comment by fgl27** [comment]
technically yes, but this is the type of thing that gets apps banned.

**Comment by Bricio92** [comment]
> technically yes, but this is the type of thing that gets apps banned.

yes, but for example SoundTV has this feature
