### ISSUE TITLE
Desktop Client

### ISSUE THREAD

**Issue by Bricio92** [fgl27/SmartTwitchTV#136]
Have you thought about developing a client for Windows Desktop?

**Comment by fgl27** [comment]
Not really no future plans to create a desktop as people prefer using the official Twitch site on desktop.

The app technically works on a browser, isn't the same but it does see here 

https://fgl27.github.io/SmartTwitchTV/release/index.html

Other option is the official support of Windows 11 to APK, again isn't the best but works better then on the browser, you can download the APK from releases

https://github.com/fgl27/SmartTwitchTV/releases

**Comment by fgl27** [comment]
this video explains how widows 22 apk support works and how to side load apk

https://www.youtube.com/watch?v=pYDWcw5DCSs

**Comment by Bricio92** [comment]
Yes, I tried to use the browser web app but it still has the ads problem.

**Comment by fgl27** [comment]
Yes not possible to avoid that on the browser.
