### ISSUE TITLE
Displays advertisements even when you are subscribed to the channel (Latin America).

### ISSUE THREAD

**Issue by juanch01983** [fgl27/SmartTwitchTV#137]
Displays advertisements even when you are subscribed to the channel (Latin America), and also shows them when you have the internal proxies active. (Latin America too).

**Comment by fgl27** [comment]
The app can't prevent ads or use yours sub privilege's Twitch doesn't allow..

**Comment by juanch01983** [comment]
I understand, I thought it did, because the official client does block advertisements when I am subscribed to a particular channel.

**Comment by fgl27** [comment]
Yes I know but this isn't an official app, twitch protect them and they users by limiting third party access.
