### ISSUE TITLE
Picture in Picture Quality issue

### ISSUE THREAD

**Issue by Supernoodles1990** [fgl27/SmartTwitchTV#138]
When i have two streams open via Picture in Picture the Main (Big) stream quality lowers from 1080p 60 down to 480p 30 and around 2mbps bitrate.

I have all settings related to multi streams set to unlimited and no other restrictions enabled.

I am using a Chromecast with google tv device.

**Comment by fgl27** [comment]
What are the net speed/ activity values.
This seems to be a network issue, low speed.

**Comment by Supernoodles1990** [comment]
Before opening a second stream

https://imgur.com/a/Rqjjapa

After opening a second stream via PiP 

https://imgur.com/a/IDr9XvM

**Comment by Supernoodles1990** [comment]
My home connection is 80/20 and my Chromecast gets about 70/15 on a speed test

**Comment by fgl27** [comment]
Net speed isn't the issue.

That device isn't supposed to have the performance to play two 1080p60 at same time.

What happens if you leave the settings at default.

Main player unlimited and small at 480p?

**Comment by Supernoodles1990** [comment]
it use to just play the big screen at whatever the source resolution/fps was and the small one use to play in around 480p
as far a i know i havent changed any settings. ive tried what you recommened and i still have the same result

**Comment by fgl27** [comment]
I don't know then, there was no change on the behavior of this feature for a long time.

Try to erase/clean app data and see if that fixes it.

**Comment by Supernoodles1990** [comment]
I'll give that a try tomorrow and report back :) 

Thanks for the help

**Comment by Supernoodles1990** [comment]
So I've done some testing after clearing app data and the issue is still the same but I've found some streams for whatever reason will run at 720p / 30 instead of being capped down to 480p / 30 

So for example if I open say KaiCenat and Summit1g both will report as 480p / 30

If I open LCK and Valorant_jpn both will report as 720p / 30

If I open Summit and LCK then Summit will be 480p / 30 and LCK will be 720p / 30

This is with all settings at default nothing changed at all

**Comment by fgl27** [comment]
this is a performance related issue.

What is the defaults codec configuration of yours device? let me see it settings -> blocked codecs.

Maybe disabling the sw codec this may solve.

**Comment by Supernoodles1990** [comment]
https://imgur.com/a/MdBQPpW

**Comment by fgl27** [comment]
try to disable 'c2.andorid.*'  codec and tell the behavior.

**Comment by Supernoodles1990** [comment]
That made no difference sadly.

The only way I've been able to force both streams to be for example 1080 if I wanted that is to block all other resolutions

**Comment by Supernoodles1990** [comment]
So blocking everything other than 10xxp / 9xxp / 7xxp allows picture in picture to keep the main stream at whatever the source resolution / bitrate is which works perfectly for what I wanted.

On 4 way display there's still an issue where all 4 streams drop to 480p even with one stream in the bigger picture with chat mode but I barely ever use that mode anyway so it's not super important.

Maybe Google have changed something with android 12 on the Google TV that's broken this stuff :/

**Comment by fgl27** [comment]
Ok thanks for the test.

I don't know the source of the issue, will ask google player devs to see if they know what is going on.

Update here when I have news.

**Comment by Supernoodles1990** [comment]
This is working perfectly for picture in picture

50/50 player seems to set one stream to max source and the other to 480 or 720 but when I press the down arrow to switch the secondary stream to be the primary it doesn't switch it to 1080 or whatever the source is and lower the original one if that makes sense?

Same situation with 4 way player it sets all 4 to 480p (with settings set to 720p / 3mb) which I understand because it's very performance demanding but I think (I might be wrong) it used to make the main stream (with chat beside it) source quality and the other 3 lower?

**Comment by fgl27** [comment]
PP, bottom from 50/50 and any multistream player are considered "Small players" the resolution/bitrate is controlled by the 'Resolution - Small players' and 'Bitrate - Small players' from bellow settings.

![image](https://user-images.githubusercontent.com/13755892/220956281-f7de9f59-fbe3-49b3-8635-9be12a5ade48.png)


That was done by design technically you can try to change, but on multistream I don't think it will work.

On my test I tried a few devices to understand that on multistream mode all players need to stay on a lower resolution to avoid the app freezing.

The only devices that don't have that issue are modern phones and the Nvidia shield almost all TV devices are very low end unfortunately.


Thanks for the help will release a final version with that fix.

**Comment by Supernoodles1990** [comment]
Thank you for the fix and insight :) 

I mostly use Picture in picture and this fixes that so I'm more than happy.

**Comment by fgl27** [comment]
On the future I'll add a separated control for the resolution of the Main or Big player on multistream.

**Comment by fgl27** [comment]
A app with this change was released.
