### ISSUE TITLE
audio vidéo desync

### ISSUE THREAD

**Issue by CrNMGuy** [fgl27/SmartTwitchTV#140]
**Describe the bug**
Got permanent audio vidéo desync on streams, while original Twitch Android TV app is perfectly sync

What to provide to investigate ?

Device TCL smart TV pro
Android 11

Just noticed that last apk update got a huge improve on app crash !

**Comment by fgl27** [comment]
the player should auto sync audio and video.

share a quick recording (phone camera is fine) from twitch app and this app same stream showing the diference to see If I can understand it better.

If the app is crashing for you isn't the app fault, on any of my device it never ever crashes.
