### ISSUE TITLE
FFZ emotes not working 

### ISSUE THREAD

**Issue by Supernoodles1990** [fgl27/SmartTwitchTV#141]
**Describe the bug**
FFZ emotes are blank when someone uses them in chat and if you open the emote menu in chat "FFZ Global" doesn't load any emotes it shows the emote names but not the images and if you go to FFZ streamer that says "this emote list is empty" bttv and 7tv work fine.

**To Reproduce**
Steps to reproduce the behavior: just try to load the FFZ emote menu in any channel 

**Expected behavior**
Emotes display in chat and in the emote menu
 
 **Device:**
 Google TV (Chromecast)

**Additional context**
The FFZ twitter mentions that they've done some server migration recently so that may be related

**Comment by fgl27** [comment]
Yes they change something on they API regarding URLs, I need to update a line on the code will do it later. 👍

**Comment by Supernoodles1990** [comment]
Thanks :)

**Comment by fgl27** [comment]
done thank you!
