### ISSUE TITLE
ancillary services

### ISSUE THREAD

**Issue by BoBox000000** [fgl27/SmartTwitchTV#142]
**Describe the bug**

There is no auxiliary service, why this is displayed

 **Device:**
 - TV Manufacture Device: Xiaomi TV

**Screenshots**

![6D858C53C9BE7D51FA928F47A6FED182](https://user-images.githubusercontent.com/127586178/227706040-fb0b9104-9ad9-46a4-b663-b67eb10ca89a.png)

**Comment by fgl27** [comment]
Because you have enable am accessibility service on the settings of yours TV.

Check yours TV settings .... Device preference... Accessibility.

If you can't find one on the app settings you can disable warnings.
