### ISSUE TITLE
Feature Request: Hide thumbnails

### ISSUE THREAD

**Issue by Supernoodles1990** [fgl27/SmartTwitchTV#144]
Hey again @fgl27 I was wondering if it was possible to make a feature so that we can blur or hide stream thumbnails for certain games?

So for example with FFZ you can hide thumbnails for a catagory and it just shows up like this.

https://www.reddit.com/r/ffxiv/comments/qndsnp/for_any_avid_twitch_viewers_remember_ffz_has_a/

Thank you in advance for anything you can do :)

**Comment by fgl27** [comment]
This is something that is already on the TODO list

https://github.com/fgl27/SmartTwitchTV/blob/master/apk/TODO.md#featured-request-list

I will inform you here the day is done.

**Comment by fgl27** [comment]
this feature was added.
