### ISSUE TITLE
VOD Chat not moving after a few messages

### ISSUE THREAD

**Issue by RyanSnow25** [fgl27/SmartTwitchTV#145]
Live channel chat moves as usual, but when I view a VOD, the VOD chat moves then stops at a certain point. This has been happening since yesterday (May 4, 2023).

Using a Xiaomi Box S on a Sony TV.

**Comment by fgl27** [comment]
What vod exactly?

**Comment by RyanSnow25** [comment]
At first I noticed it happening to a vod of a streamer of her May 4 stream, then I checked another streamer's vod (same date, same thing). I also checked a May 5 vod, same thing. Lastly, I checked a stream from weeks ago, same issue. It all happens in the 2 minute mark from what I observed.

**Comment by fgl27** [comment]
I managed to reproduce the issue, twitch blocked access to one of they chat vod API.

I add the above workaround and pushed an update.

Test let me know.

**Comment by fgl27** [comment]
This is a temp maybe permanent fix as there is no other option.

This workaround will allow the vod chat to work but may not show all chat messages in case there are too many (50+) in a single second, something that isn't a big issue as the app can't display on the screen that many anyway, so skip some will not be noticeable.

On regular chats where we have just a few msg a second all will show OK.

I just wanna document this here.

**Comment by RyanSnow25** [comment]
Tested it on the May 4 vod and 2 month old vod, both back to working as intended. I don't usually tune in to the chat of streams with many viewers/messages so I can't say I'll notice the workaround. I'm closing the issue; reopening it/opening a new one if I find something related to it again.

Thank you :)

**Comment by fgl27** [comment]
> This workaround will allow the vod chat to work but may not show all chat messages in case there are too many (50+) in a single second, something that isn't a big issue as the app can't display on the screen that many anyway, so skip some will not be noticeable.

I push a change to not use the workaround , but on future the chat may stop working again if so let me know @RyanSnow25
