### ISSUE TITLE
Live Chat not working

### ISSUE THREAD

**Issue by sirjes** [fgl27/SmartTwitchTV#146]
I'm attaching a pic of the error i get, i think it started about 3-4 days ago. It's for any channel.
![IMG_2138](https://user-images.githubusercontent.com/6137363/236594012-cadbc0c9-d19b-40d7-a315-153591afd04f.jpeg)

**Comment by fgl27** [comment]
Not something replicable. Chat if fine here.

Try to delete the user and add again.

If that doesn't solve check yours network.

**Comment by sirjes** [comment]
Now that you mentioned deleting user and adding again, i think it might have been that i changed my name on twitch that might have caused it.

**Comment by fgl27** [comment]
and re-adding resolves?

The user name itself doesn't matter to logging in to chat, as the app uses the authorization key.

**Comment by sirjes** [comment]
Yup, I deleted but then the app wouldn't load past the loading screen, so had to delete the app and reinstall and add user.

**Comment by fgl27** [comment]
you can just clean the app data to fully erase the app, maybe something else was bugged as deleting users doesn't cause that...
