### ISSUE TITLE
Live chat not loading

### ISSUE THREAD

**Issue by Sonia-js** [fgl27/SmartTwitchTV#147]
**Describe the bug**
Not sure if this is a known issue, it might already been worked on. When watching a live stream the chat doesn’t load. It keeps saying connecting timeout and failed. The chat works fine on vods, it’s just live streams not working. Have noticed it’s been like this for sometime now. 

im using foxtel now box’s plugged into a Samsung and a Panasonic in different rooms. Not sure if you can see my attached photos. 

![0A9782AC-6754-4283-BD4A-2DC6EC02A838](https://github.com/fgl27/SmartTwitchTV/assets/123785838/227f10db-aaf7-4288-bd37-4f4eba21c56b)
![3E3D4CD8-0BFD-4A5A-8B18-6DCFF20A6F8A](https://github.com/fgl27/SmartTwitchTV/assets/123785838/e5f9fd42-2fb4-40c3-a5b2-08364af0d735)

**Comment by fgl27** [comment]
Chat is fine for me

![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/aaa63200-bc7b-4e3d-b666-1552e55f67d6)

This is something related to your network or user.

If have added a user try to delete it and read to see if works.
