### ISSUE TITLE
Live Streams not working following latest update

### ISSUE THREAD

**Issue by AZEK611** [fgl27/SmartTwitchTV#149]
**Describe the bug**
I cant stream anything from the app when accessing from the tv. Happened after the latest app changes today. No errors in clips and VODs, just live streams

**To Reproduce**
1. Go to Live
2. Click on any live feed

**Expected behavior**
Loading a stream that never happens to load. Just 6 hours ago I can stream comfortably, but after the most recent changes, it just wont work at all.

**Screenshots**
I can provide a video if that helps.
 
 **Device:**
 - TV Manufacture Device: Chromecast with Google TV
 - OS version 12

**Additional context**
Cleared cache, user data, reinstalled the app, all to no avail.

**Comment by dekoration** [comment]
same issue here

Device:

TV Manufacture Device: Sony Bravia 4K VH21 SDK: 29
OS version: Andriod TV-OS-Version 10

**Comment by CryRocks** [comment]
same here

I'm using Chromecast HD with latest Android 12 Updates (security patch 1. April,  STTE.230319.008.R1)

**Comment by rtom098** [comment]
Same for me on Google Tv. The overview shows the streamers thumb pics and how long they streamed but clicking on one it doesn't load any live stream video. Worked fine before

**Comment by thro86** [comment]
Same issue. Nvidia shield (console not an Nvidia Shield TV)

**Comment by fgl27** [comment]
Is all ok now just update.

**Comment by thro86** [comment]
> Is all ok now just update.

Just want to let you know how much I appreciate all your hardwork these past couple years. Without your app I wouldn't be able to enjoy twitch like I do. Thank you very much. For every person who doesn't express their gratitude just know there are dozens of others who are appreciative.

**Comment by AZEK611** [comment]
> Is all ok now just update.

Thanks as well for providing this wonderful app and giving us an option of watching twitch without the hassle of the official android tv app.
