### ISSUE TITLE
Global sub badge showing when we have a channel badge that should replace it

### ISSUE THREAD

**Issue by fgl27** [fgl27/SmartTwitchTV#150]
Open a channel, exit the channel open the channel again it must show the issue:

![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/85528dca-6425-48dd-8290-5449897911f7)

expect to see these badges, replacing the "star" badges

![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/3b2c89f4-6604-44e0-b066-dbd489722f06)

@bitteL3BN follow this issue.

Originate from https://github.com/fgl27/SmartTwitchTV/issues/148

**Comment by fgl27** [comment]
I push a fix...
Update the app to the latest version if you see any issues let me know.

@bitteL3BN

**Comment by bitteL3BN** [comment]
Thank you so much for fast fixing this bug.
Seems to work like a charm now. 

By the way I switched from your tizenos app finally to the android one and just wanted to say I really appreciate your work! Awesome dev. 🙂
