### ISSUE TITLE
Vod sub-only feature

### ISSUE THREAD

**Issue by Bricio92** [fgl27/SmartTwitchTV#151]
Could you may implement the function of watching vods for subs only in the future, as S0unTV app for android TV?
https://github.com/S0und/S0undTV

Thank you so much

**Comment by fgl27** [comment]
If you and they are OK with piracy fine for you, but if something is behind a paywall and you give someone access without payment you are pirating the content.

is that simple.


I am particularly not OK with that, as I don't wanna prevent everyone from using this app just for a simple feature, believe me, if someone reports an app promoting piracy it will be banned.
