### ISSUE TITLE
Option to make background from highlighted messages transparent

### ISSUE THREAD

**Issue by bitteL3BN** [fgl27/SmartTwitchTV#154]
Highlighted messages hide too much from the screen when I watch in fullscreen mode with enabled chat. Might be a good feature if one would had the option to change the opacity from the background of highlighted messages. If this can't be made transparent maybe give the option to disable highlighted messages in fullscreen mode.

**Comment by fgl27** [comment]
Yes we can sync the transparenci across those msg.

**Comment by fgl27** [comment]
the above fix the issue, when I push this change to the app I let you know.

**Comment by fgl27** [comment]
this feature was added.
