### ISSUE TITLE
"Forbbidden content..."

### ISSUE THREAD

**Issue by Bricio92** [fgl27/SmartTwitchTV#155]
In some channels it's present this message and doesn't reproduce the stream:
- 
![Immagine 2023-06-22 164225](https://github.com/fgl27/SmartTwitchTV/assets/91467148/d1007183-7fde-4123-b2ec-423cc5263d43)
"Forbbidden content, this is restricted in your region or restrained to the official Twitch app"

Devices:
 - Fire TV Stick - Android TV (last versions)

**Comment by fgl27** [comment]
isn't the message self-explanatory?
