### ISSUE TITLE
Washed out colors

### ISSUE THREAD

**Issue by DrunkFruitBat** [fgl27/SmartTwitchTV#156]
**Describe the bug**
Washed out colors after I re-installed it. I haven't updated it in a while and when I did I noticed that the colors were no longer vibrant and rich. It could be my Android TV (I reformatted it) I just never experienced this before.
 
 **Device:**
 - TV Manufacture Device: Android Tv

**Comment by fgl27** [comment]
I have no idea.

The app doesn't change the picture quality so it must be yours device configuration.

**Comment by NightHammer1000** [comment]
Sounds like an HDR Issue to me.

**Comment by fgl27** [comment]
Yes HDR, color space something may have changed and is causing issues.

But the app can't control those, they are device specific settings.
