### ISSUE TITLE
Ads Advertising on live streams and vod, when I still have on several channels

### ISSUE THREAD

**Issue by felipesan1** [fgl27/SmartTwitchTV#158]
**Describe the bug**
When I watch live channels, advertising is coming out and I have turbo and subscriptions

I don't know if it's because it's a third party, but look at that detail.
 I know that the app is free and it is appreciated 
 **Device:**
 - TV Manufacture Device: TV TLC..
 - Os version Android tv 11

**Comment by fgl27** [comment]
The app doesn't try to block ads and can't use your Turbo or sub privilege.

Twitch doesn't allow third-party access to most of the user features.

Here you can see what access the app gets from your user:

https://github.com/fgl27/SmartTwitchTV#authorization

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/172

**Comment by Sam-arch99** [comment]
Same issue on my Samsung TV (Tizen OS). Most of the time the app will not be usable anymore after an AD and I have to close/restart the app.

**Comment by fgl27** [comment]
@Sam-arch99 I guess you don't know how git works and you think this is just like chat or some random Reddit but isn't 

when you go to issue and post a 'me too' comment you aren't adding anything new, we all already know that there is an issue, and the only thing you are doing is to call other attention, we aren't here to give you attention.

when you post comments on the issue you send notifications, emails etc to all involved, just last night you sent hundreds of those to a lot of people.

don't do that anymore, we know that there is a problem and your posting 'me too' isn't helping.

If you have anything new to add please do, but if you don't don't.

for today I will only delete your comments next time I will just ban you.

for Samsung related issue always post on the other repo

https://github.com/fgl27/smarttv-twitch/issues/277#issuecomment-1716901363
