### ISSUE TITLE
Frame drops with 60fps content using AI enhanced upscaling on nvidia shield pro

### ISSUE THREAD

**Issue by kurtdh** [fgl27/SmartTwitchTV#16]
**Describe the bug**

Keep player statistics on and watch frames drop by 50 at a time when AI enhanced upscaling is enabled on nvidia shield and while watching 60fps content. 

**To Reproduce**
1. Go to any stream running 60 FPS. 
2. Turn on Ai enhanced upscaling on your nvidia shield pro 2019. 
3. Turn on player statistics and watch frames skip by 50 frames at a time. 

**Expected behavior**
I expect there to be no skipped frames. This is not an nvidia problem because it’s not an issue on nvidia native apps, and it was confirmed as a specific app issue by nvidia staff. 

**Screenshots**

https://imgur.com/a/k8b5pUT

 
 **Device:**
 - TV Manufacture Device: Nvidia Shield pro 2019

**Additional context**

**Comment by fgl27** [comment]
> I expect there to be no skipped frames. This is not an nvidia problem because it’s not an issue on nvidia native apps, and it was confirmed as a specific app issue by nvidia staff.

Let me see that conversation?

The app uses this player API https://github.com/google/ExoPlayer/ with the player that all manufactures must use for validade they devices, so this fatures from nvidia must happens on others tipe of app, after all is not something constant (is one drop it 10 20 seconds).

Youtube can also detect dropped frames what is the result on youtube videos with similar resolution/frame rate?

![YouTube_20200827_154406](https://user-images.githubusercontent.com/13755892/91482355-52258200-e87c-11ea-873e-cdce8d3b2839.png)

This is something that needs to be addressed on the player repo, but as I don't have the device to do all the follow up that they will ask, maybe you wanna to open a issue there, I will add the proper app info and generate any test apk, and you do the test and generates all the logs that will be necessary.

Something what I did here https://github.com/google/ExoPlayer/issues/7411

**Comment by kurtdh** [comment]
Here’s the screenshots from the nvidia staff I had a conversation with.   
  

  
  
  

  
  
  

  
 I have watched 1080p 60fps content on YouTube app with AI enhanced upscaling on. I get 0 dropped frames, so the native YouTube app works just fine. The only issues I’m having is with your app and with the smart YouTube tv app. If the smart YouTube tv app also uses exoplayer, it’s likely an exoplayer issue. I will create an issue on their GitHub and send you the link.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by kurtdh** [comment]
Interestingly enough, I’ve been able to reproduce this bug with the official YouTube TV app as well. I’m notifying nvidia about it.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by fgl27** [comment]
You didn't attached any image. Just drag and drop to a post.

**Comment by kurtdh** [comment]
![IMG_2036](https://user-images.githubusercontent.com/26121469/91487681-bc85f480-e873-11ea-8eec-a4ebdecbb819.PNG)
![IMG_2034](https://user-images.githubusercontent.com/26121469/91487682-bd1e8b00-e873-11ea-8f10-69676a6040a9.PNG)

**Comment by kurtdh** [comment]
I submitted an issue with exoplayer as you requested at the following link:

https://github.com/google/ExoPlayer/issues/7821

Seeing as how I can reproduce this in the Youtube TV app though, I'm not certain the issue is specific to exoplayer..

**Comment by fgl27** [comment]
I advise you to close that as this is a device issue.

And ask nvidia to direct communicate with google if they think is a problem on google side.

**Comment by fgl27** [comment]
The app can play 4 simultaneous 1080p@60 streams with zero drop frames, and with one stream o. That special mode it drops frames, that is not a app.issue, probably not even exoplayer issue.

**Comment by kurtdh** [comment]
> 
> 
> I advise you to close that as this is a device only issue and happens to YouTube app.
> 
> And ask nvidia to direct communicate with google if they think is a problem on google side.

To be clear, it's happening in the YouTube TV app, not the YouTube app. But sure, I'll close this issue, because I agree it sounds more like an nvidia shield issue than a specific app issue.

**Comment by fgl27** [comment]
I don't think `YouTube TV app` uses exoplayer they use a in app mediaplayer implementation specific to youtube, I ask you to close the issue on exoplayer repo not here, even that there is noting I can do here, I don't have the device I don't think is a app issue.

As you have direct contact with Nvidia staff ask them to revise and let they know about the 4 way playback that is perfect that proves ta well optimized app.

**Comment by kurtdh** [comment]
> 
> 
> I don't think `YouTube TV app` uses exoplayer they use a in app mediaplayer implementation specific to youtube, I ask you to close the issue on exoplayer repo not here, even that there is noting I can do here, I don't have the device I don't think is a app issue.
> 
> As you have direct contact with Nvidia staff ask them to revise and let they know about the 4 way playback that is perfect that proves that the app is well optimized.

Yes I reached out to them with the updates. I also submitted a bug report to Google about YouTube TV. The hope is, if the app developers can recognize an issue in their apps, they can work directly with nvidia to fix the issue. I would like to keep the exoplayer issue open, because if others can replicate the same issue, the exoplayer developers should work with nvidia to figure out what is wrong, and by fixing it, will likely fix it for all the other apps that have issues as well.

**Comment by kurtdh** [comment]
Upon further inspection, it looks like the AI upscaling is constantly flickering between off and on. I guess this could be causing the skipped frames?
  

  
Nvidia dev provided an explanation:
  

  
“If the frame rate of the media is going above 60 at times, the upscale will turn off for those frames. I suspect your video is on the border crossing the boundary. We have a bit of margin on top of the 60 but not much. Is it possible the video is changing frame rate above 60 when this happens?”
  

  
If there’s a way in your app to limit 60fps streams to strictly 60 and have it never go above that, it could be a potential fix..? Thoughts?
  

  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by kurtdh** [comment]
Nevermind. Changing a stream to 720p 60fps fixes the problem. It’s only an issue with 1080p 60fps streams. This tells me it’s not an issue with streams going above 60fps since 720p 60fps works just fine.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by kurtdh** [comment]
Actually scratch that. AI upscaling DOES continue to flicker on and off in 720p 60fps content as well. It just doesn’t skip frames.   
  

  
So, the nvidia dev might be onto something. The streams are going above 60 FPS, and it’s going above the built in threshold nvidia built into AI upscaling. Not sure if this is an exoplayer thing, or a way that Twitch streams are encoded? Or if there’s a way to cap it at 60fps? Not sure, I’m not a coder.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by kurtdh** [comment]
720p 60fps: AI upscaling flickers on and off constantly.    0 dropped frames.   
  

  
1080p 60fps: AI upscaling flickers on and off constantly. 50 dropped frames every 10 or 15 seconds.
  
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by fgl27** [comment]
how did he tested that is above? can the nvidea staff just test the app on the device and properly debug and not guess what is going on?

when I debug the 2017 shield I get this when playing a streams...

1080p60 the logs display the bellow repetitively

`D NvOsDebugPrintf: NVMEDIA: FrameRate(for last 120 frames) = 60.000240, AvgFrameRate = 60.000240 `

same stream but @ 720p60

`D NvOsDebugPrintf: NVMEDIA: FrameRate(for last 120 frames) = 60.000240, AvgFrameRate = 60.000240 `

same stream but @ 720p30 the logs are full of

`NvOsDebugPrintf: NVMEDIA: FrameRate(for last 120 frames) = 30.000030, AvgFrameRate = 30.000030 `

And there is 0 dropped frames so I can only assume what plays is what is be received.

**Comment by kurtdh** [comment]
No, I took his response from another reddit thread where a guy was having a similar issue with the tivimate app. Check out the reddit thread here for more context. I also copied and pasted your logs and sent it to him to see if that’s above the Ai upscaling thresholds.    2017 shield doesn’t have AI upscaling, but your logs showing FPS should be the same on 2019 shield.   
  

  
 https://www.reddit.com/r/ShieldAndroidTV/comments/ihzt74/issue_with_ai_upscale_since_update/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by kurtdh** [comment]
And to be clear, I think these might be two different issues. As I listed in my previous post, AI upscaling flickering on and off seems separate from the skipping frames issue since 720p 60fps does flicker AI upscaling on and off with 0 skipped frames and 1080p 60fps flickers AI off and on WITH skipped frames.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by fgl27** [comment]
When I set the device to 1080p30 the log is the same for a 1080p60 stream... So I can only assume the stream is perfect at 60, as the device reports what is be playing.

2.5/1000 will never be above any threshold for something like this, if was at least a few frames maybe but 0.00024 no.

**Comment by kurtdh** [comment]
Factory resetting the shield fixed the problem. Hmm. If it happens again, hopefully I’ll have an idea of what triggers the problem. I’ll keep you in the loop. Nvidia staff helped troubleshoot it last night with me.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by kurtdh** [comment]
I figured it out! It’s adjust for overscan. If you change this in display settings of the shield to anything other than default, you will get dropped frames with Ai upscaling enabled. Set it to default, and the dropped frames go away. I’m alerting nvidia of this so hopefully they can hotfix it.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by kurtdh** [comment]
Now that I figured out that issue, I would like to solve the AI flickering on and off issue. Can you tell me how you got those logs of the frame rate? I’m going to dive into it a little deeper perhaps since nvidia seems intent on fixing the issues.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by fgl27** [comment]
Connect via adb, and use the command `logcat`.

If you only wanna to see lines that contains `NvOsDebugPrintf` use  `logcat | grep NvOsDebugPrintf`

But this last in't advised, as yours 2019 device may not use the same word (NvOsDebugPrintf) as the 2017 version and also there may be a very specific log that happens when the drops frame happens and you will miss if you `grep` a line.

**Comment by kurtdh** [comment]
Ok. I am going to try to figure this all out so I can track down why AI upscaling is flickering on and off. The lead dev at nvidia in charge of upscaling saw a video I sent him and he thinks it’s almost definitely the video going over the threshold which is set to 60.01. Your logs only show the average frame rate not the max frame rate. I also tested on the official twitch app and it flickers there too. This tells me it might have something to do with the way Twitch encodes their streams, and that it’s a variable frame rate that goes above the threshold. Nvidia devs are considering increasing the threshold.   
  
  
  
  
  
Sincerely,
  
Kurt Hardeman
  

        
  

  
  
>

**Comment by fgl27** [comment]
I don't think is above 60. I think nvidia devs didn't properly tested the feature before release and should do better.
