### ISSUE TITLE
Block unnecessary languages of streams

### ISSUE THREAD

**Issue by MaximUSNG** [fgl27/SmartTwitchTV#162]
Hello. There have already been requests to add the ability to select several different stream languages (#21, #132). Unfortunately, the Twitch API does not provide this option. But since the possibility of blocking channels and categories has appeared, then maybe this method will work for languages too?

**Comment by fgl27** [comment]
it's possible, but not practical.

If one filter en for example, most content is en you will have to, download all filter all, make another call filter then again an again until you have some content to show.

With is not practical the app isn't ready for that, may work ok for one filter but not too all, I can't make a feature that only partially works.
