### ISSUE TITLE
No chat messages on VODs

### ISSUE THREAD

**Issue by Vlangusy** [fgl27/SmartTwitchTV#163]
**Describe the bug**
I don't see any text in chat while watching a VOD (neither chats nor any notifications about connecting to chat, just no text at all). There is still the dark background of the chat visible, The chat works with livestreams, only not with VODs.

**To Reproduce**
Start playing any VOD and have chat enabled.

 **Device:**
 - some Philips TV from around 2015
 - Android TV 5.1.1

**Comment by fgl27** [comment]
fix it, just close and reopen the app to fix it.

**Comment by Vlangusy** [comment]
Ooh, now I closed the app with the Exit -> Close option from the app's menu and it helped, the chat is working, thanks.
Before I tried closing it by holding the back button, cleared cache, removed the app data which also closes the app but it didn't help.
