### ISSUE TITLE
Twitch ads 

### ISSUE THREAD

**Issue by Davroju** [fgl27/SmartTwitchTV#166]
**Describe the bug**
Getting twitch ads like on twitch platform 

**To Reproduce**
Run the app and get ads

**Expected behavior**
Never got ads before, been using this App about 2 years 

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield
 

**Additional context**
Is this intended, are you now pushing twitch ads through?

Thanks

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/165

Nothing to do here, read above

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/172
