### ISSUE TITLE
Getting ADS!

### ISSUE THREAD

**Issue by Bubblegutknott** [fgl27/SmartTwitchTV#168]
**Describe the bug**

**To Reproduce**
4. See error something doesn't work

**Expected behavior**

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield, Xiaomi Mi box I II III IV, etc...
 - Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]

**Additional context**

**Comment by ClientUnknown** [comment]
Can confirm, just started happening to me a minute ago, was fine all day. Never seen an ad on this app before.

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/166

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/172
