### ISSUE TITLE
OOS on streams encoded in 900p60

### ISSUE THREAD

**Issue by d4niel-P** [fgl27/SmartTwitchTV#17]
**Describe the bug**
Audio and video is slightly but noticeable out of sync when streaming content encoded in 900p60.
I haven't spotted any oos on channels streaming in other resolutions. Oos disappears after switching quality to 720p or lower on affected channel (it's only workaround though, due twitch's crappy encoding quality takes a huge hit whenever stream is not in source resolution).

**To Reproduce**
Examples of content creators usually streaming in 900p60:
- Emongg
- FRAN
- kragiee

**Expected behavior**
No noticeable OOS . ;)
 
 **Device:**
 - Xiaomi Mi box IV
 - Android 9

**Comment by fgl27** [comment]
Device issue read more about that here
https://github.com/google/ExoPlayer/issues/7411

**Comment by d4niel-P** [comment]
Issue has been fixed in latest beta firmware (PL.3015) for Xiaomi Mi box 4.

**Comment by fgl27** [comment]
My device is on pl.2696 and there is no update yet. How they are sharing that beta?

**Comment by d4niel-P** [comment]
Afaik Xiaomi has only closed beta program. I got update.zip form Telegram group. I can provide the link if you like.
https://www.reddit.com/r/MiBox/comments/jb42pl/new_beta_rolling_out_for_mi_box_s4k/

**Comment by fgl27** [comment]
OK, if you can share a link of the zip I appreciate I don't wanna really use telegram, if is something that needs to be shared private use my email fglfgl27@gmail.com
Thank you.
