### ISSUE TITLE
sometimes it's showing ads during and at the start of a stream

### ISSUE THREAD

**Issue by CryRocks** [fgl27/SmartTwitchTV#170]
**Describe the bug**

Not sure when or how often, but since yesterday I sometimes got an ad during a stream or shorty after clicking on one

**To Reproduce**
Not sure, since it happens randomly, just watch a stream and it may happen for you too?

**Expected behavior**
probably no ads I guess
never really saw ads until yesterday

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.

don't have one currently
 
 **Device:**
 - TV Manufacture Device: Google chromecast
 - Os version: Android 12/TV (latest)

**Additional context**
I also have twitch turbo, but I don't think this app can even make use out of it.

**Comment by Bubblegutknott** [comment]
Can confirm. I am getting ads also. Android TV OS user here.

**Comment by warzieblue** [comment]
Experiencing the same. Android TV on Sony BRAVIA. Also have Turbo, but the channels I have been watching are ones that I am already subbed to regardless. So ads are still coming through despite both of those.

**Comment by Alicyl** [comment]
Chiming in to say that I also started seeing ads today, and none of the proxy settings are working against them.

**Comment by DeicPro** [comment]
Amazon updated their ad stuff. Any modded Twitch app shows adds from yesterday.

Also I'm getting ads even in channels where I have a subscription.

**Comment by fgl27** [comment]
There is hundreds of issues about the same thing stop opening issues about ads.

If you wanna work on a solution open a solution issue but you here are only competing.

More info follow the links

https://github.com/fgl27/SmartTwitchTV/issues/168#issuecomment-1703637035

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/172
