### ISSUE TITLE
getting ads even though i am turbo subscriber.

### ISSUE THREAD

**Issue by loudbacon** [fgl27/SmartTwitchTV#171]
**Describe the bug**
just recently i have started to get ads even though i am a twitch turbo sub, i have tried to re bind my account to the ap, as well as un installing the app and then reinstalling the app. i am using a sony smart tv
**To Reproduce**
4. See error something doesn't work

**Expected behavior**

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield, Xiaomi Mi box I II III IV, etc... SONY Bravia xsomething
 - Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]

**Additional context**

**Comment by Alicyl** [comment]
#170

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/170

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/172
