### ISSUE TITLE
App not starting (infinity loading)

### ISSUE THREAD

**Issue by missiah** [fgl27/SmartTwitchTV#176]
After the last update I have a infinity loading circle of Doom when I start the app 😭

Running it on fire tv stick 
Do I have to reset the app and loose all settings? 😢
![20230911_192425.jpg](https://github.com/fgl27/SmartTwitchTV/assets/57118418/e98fe857-0e41-4784-b7b9-25533bc35b01)
Version: 3.0.349

**Comment by missiah** [comment]
after random key pressing I got a menu showing up but the UI seems to be very buggy and broken

**Comment by twiikker** [comment]
I have this same problem and pressing buttons doesnt help.

**Comment by fgl27** [comment]
If you clean app data this will resolve...

but I already pushed a change to fix the problem.

**Comment by fsalata** [comment]
@fgl27 this started happening on my UN43MU6100 on Sunday.

**Comment by fgl27** [comment]
@fsalata 

This is the Android repo, which has a way for you to clean the app data, I assume you are on a Samsung TV wich doesn't have that option, this repo

https://github.com/fgl27/smarttv-twitch

Here is the help for the infinity loop on Samsung

https://github.com/fgl27/smarttv-twitch/issues/248#issuecomment-1303990563

If that doesn't help you need to reinstall the app.

**Comment by fsalata** [comment]
Thank you.
It did not work.
My issue is more similar to this one, the loading appears even before the app opens.

**Comment by fgl27** [comment]
Open a new issue on the proper repo, this is android only
