### ISSUE TITLE
BTTV/FFZ emotes not showing in chat

### ISSUE THREAD

**Issue by Naruske** [fgl27/SmartTwitchTV#177]
Ever since the last update I do not see emotes such as KEKW, EZ, NOPERS etc. in Lirik's chat.

**Comment by fgl27** [comment]
Have you looked to see if the streamer provides these emotes?

they can remove emotes from the supported list.

**Comment by Naruske** [comment]
Yeah, Lirik hasn't changed these emotes in forever.

________________________________

**Comment by fgl27** [comment]
I just look he removed from supported list

**Comment by fgl27** [comment]
https://www.frankerfacez.com/channel/lirik

https://betterttv.com/users/55ae669b911d882c66cfbfd8

**Comment by fgl27** [comment]
Or was never there sand was a global that is no longer global.

Either way not a app problem
