### ISSUE TITLE
I did not see ads before now I see ads on steams

### ISSUE THREAD

**Issue by roafhtun** [fgl27/SmartTwitchTV#178]
**Describe the bug**
Ads do show up in the app now.

**To Reproduce**
1. Go to 'any stream'
2. Click on 'click on stream'
3. Scroll down to 'Watch ads'
4. See error something doesn't work

**Expected behavior**

I did not have ads before but now I have them.

**Comment by fgl27** [comment]
Don't open issues about this

https://github.com/fgl27/SmartTwitchTV/issues/172
