### ISSUE TITLE
Ads appearing on streams subscribed recently

### ISSUE THREAD

**Issue by gempir** [fgl27/SmartTwitchTV#179]
Recently ads starting appearing on streams that I am subbed to. Is there something that Twitch changed that might cause this? I haven't had ads in years while using this great app.

I don't know many things how the player is implemented here, but I would assume as long as you are logged in in the iframe of the player then Twitch would not show you ads for streams you are subscribed to. (This happens on multiple streams I am subbed to)

Is this just a technical limitation from twitch or can there be done something to fix this?

**Comment by SuperNova911** [comment]
Same here

**Comment by gempir** [comment]
Oh yeah I'm sorry. I use both, but this issue was on my Samsung TV.
