### ISSUE TITLE
Mucha publicidad en general 

### ISSUE THREAD

**Issue by Daniharley883** [fgl27/SmartTwitchTV#180]
En el Amazon Fire TV 4K Max, basado en Android 9, antes no saltaba nada de publicidad; era una de las mejores cosas que tenía la aplicación. Desde que cambiaron algo en Twitch y las dos últimas actualizaciones de la app, salta publicidad constantemente y no doy con la manera de bloquear la publicidad. ¿Hay posibilidad de que se vuelva a bloquear dicha publicidad?

**Comment by Bricio92** [comment]
Same problem. On my Fire TV Stick Lite and 4K.

**Comment by fgl27** [comment]
Thec ads are from twitch, and it never blocked ads, was twitch not sending to you.
