### ISSUE TITLE
Ads are no longer being blocked.

### ISSUE THREAD

**Issue by ACodingGenie** [fgl27/SmartTwitchTV#19]
Hello, it seems like ads are no longer being blocked in the app. I am not sure how much control you have over this situation since Twitch is pushing their boundaries in order to make sure users see ads. But Ads are playing as soon as you select a stream and even during the stream when the streamer activates them. Is it possible to fix this even though Twitch embeds them directly into the stream itself?

Thanks.

**Comment by lilchina** [comment]
What's frustrating is it plays even on channels  I sub to.  If I refresh  it plays more ads on channels  I sub to, grrrr, why pay if you still get ads. P.s, on website  ads doon't play on channels I sub  too. So I  guess on browser it checks  to see if sub if not  embeds ads in stream. 🤔

**Comment by ACodingGenie** [comment]
I not sure what it even is. They must've pushed out an update recently or something, ads are slipping past UBlock origin. If it gets past Ublock then there's really no hope imo.

**Comment by fgl27** [comment]
they are making ads part of the stream it self, that is it. the only know workaround is not show the add but that means a black screen until the add has ended with can be 15 to 60 seconds of noting, plus after something is show there is a desincronizations, so is technically worst not to show the add and show a black screen.

the only way to inform you are a sub is by using the authorization key from the official app or website, the authorization key generate via third party  apps can't be used to inform if you are a sub or a turbo or wherever that can prevent ads from showing as if the app does the stream will not play.

So only the official app or website can ṕrevent you from see ads when you really deserve that.

Use the website authorization key outside the website can get yours account banned, and if used on this app this app banned also, that includes my twitch account be banned too.

If they are crazy about adds like this is possible that they do ban user and or me on that case.

**Comment by ACodingGenie** [comment]
Yeah I kind of expected that with the way Twitch is handling this whole ad stuff now. It a little bit crazy but I guess I would rather watch a stream on my TV with some ads versus no stream at all. Appreciate it Felipe.

**Comment by fgl27** [comment]
let open to prevent issue opening span

**Comment by fgl27** [comment]
ads have stopped, maybe my region over 24h noting.

If you have let me know... how often and what region?

**Comment by noriea** [comment]
Not sure if this helps, but there's a way to block ads in ublock again for now. https://www.reddit.com/r/uBlockOrigin/comments/j2648i/how_to_kill_ads_on_twitch/  

Not sure if this helps here though.

**Comment by fgl27** [comment]
> Not sure if this helps, but there's a way to block ads in ublock again for now. https://www.reddit.com/r/uBlockOrigin/comments/j2648i/how_to_kill_ads_on_twitch/
> 
> Not sure if this helps here though.

That was already informed to me, via email, that is how the app already uses the links to get the streams...

The process done by this function:

https://gist.githubusercontent.com/pixeltris/e78bb8f9d8a7a22665958e339b2d45dd/raw/twitch2.js 

was causing the ads in the past (some months ago not this time), so is very odd that it will prevent ads today... but they did changes things so this way may be the one that works now.

I have zero ads for over 48h without ads I can't really test for anything to prevent them, what I wanna to know is what I have asked before...

> If you have let me know... how often and what region?

**Comment by fgl27** [comment]
As no one is informing a ting about ads, I can only assume no one is getting ads so close this
