### ISSUE TITLE
7TV emotes are not working

### ISSUE THREAD

**Issue by twiikker** [fgl27/SmartTwitchTV#190]
**Describe the bug**
7TV emotes are not working/loading

**To Reproduce**
Go to stream and see they are not loading up.
When going to write to chat it says 'emote list is empty' even on 7TV global emotes

**Expected behavior**
7TV emotes to show up in chat and when opening emote list when writing to chat

**Additional information**
This has been happening for over week already

 **Device:**
 - TV Manufacture Device: Sony Android TV XE85
 - Os version: Android 9

**Comment by seth-rah** [comment]
Think there is already a pull request for this

https://github.com/fgl27/SmartTwitchTV/pull/187
