### ISSUE TITLE
No TTV LOL Proxy option anymore?

### ISSUE THREAD

**Issue by boobthecat** [fgl27/SmartTwitchTV#191]
It suddenly vanished. Did it get removed?

**Comment by fgl27** [comment]
the free version doesn't work anymore for this app.

open source app you can add any feature you want; I will not add any more proxy support, I spend days 'deving' the solution it works for some time then just stops.

and is OK for them to stop working, as they don't support third-party use of their implementation.

but if any one wanna to support this type of feature, the app is capable.

**Comment by boobthecat** [comment]
Free version? There's a paid one?

**Comment by fgl27** [comment]
If the proxy yes this app no is 100% free and open

**Comment by boobthecat** [comment]
Understood. I'm currently having to use the PurpleTV app, which sucks because it's made for phones but it's the only one working.
