### ISSUE TITLE
4-way multistream previews breaking

### ISSUE THREAD

**Issue by MightyCrusier** [fgl27/SmartTwitchTV#192]
**Describe the bug**
When using 4-way multistream feature, scrolling through streams breaks some of the previews. They get either squished and/or misplaced.

**To Reproduce**
1. Launch 4-way multistream
2. Switch to the layout with one big stream w/ chat and 3 smaller ones
3. Start scrolling through streams

**Expected behavior**
![My Great Game - My Great Capture_2023-11-21_03-18-34](https://github.com/fgl27/SmartTwitchTV/assets/39172116/8e10a704-26f5-45cc-8021-b9d53841069c)

**Screenshots**
![My Great Game - My Great Capture_2023-11-21_03-18-28](https://github.com/fgl27/SmartTwitchTV/assets/39172116/7e8e2786-85f5-419e-8c6d-d0d8d083c7d3)
![My Great Game - My Great Capture_2023-11-21_03-18-40](https://github.com/fgl27/SmartTwitchTV/assets/39172116/597e0d0c-6349-4f92-993b-2b36b2174738)

 
 **Device:**
 - TV Manufacture Device: CANAL+ BOX 4K (Skyworth Digital)
 - OS version: Android TV 10
![My Great Game - My Great Capture_2023-11-21_03-35-32](https://github.com/fgl27/SmartTwitchTV/assets/39172116/148cec68-7e48-40dc-8c8b-a9ade8cf59cc)

**Comment by fgl27** [comment]
I can see, but can't replicate it.

this is a device-specific bug, the app calculates the size and position of its player once at the stat, when you change it just uses the predefined value.

is very odd that it changes.

**Comment by fgl27** [comment]
At the start of the playback, if you exit the multi-mode, it works as expected?

I see some black bars in the first pictures between the players

**Comment by fgl27** [comment]
if you enabled the bellow settings, does it help?

![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/b61ebfc0-ca91-46c2-98c1-ed299629093b)

**Comment by MightyCrusier** [comment]
> At the start of the playback, if you exit the multi-mode, and start again it works as expected?
> 
> I see some black bars in the first pictures between the players, it should not show any in a 16by9 device screen.

Yes, it works as expected, there are no bars when playing a single stream or PiP. 

I believe in this scenario one of the streamers(in the middle of smaller ones) had their game in some weird resolution, which resulted in letterboxing. I realised this after posting, but other streams were just fine.

**Comment by MightyCrusier** [comment]
> if you enabled the below settings, does it help?
> 
> ![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/b61ebfc0-ca91-46c2-98c1-ed299629093b)
> 

Yes, this fixes the issue. It introduces playback and interface slowdowns, is that normal?

**Comment by fgl27** [comment]
> > At the start of the playback, if you exit the multi-mode, and start again it works as expected?
> > I see some black bars in the first pictures between the players, it should not show any in a 16by9 device screen.
> 
> Yes, it works as expected. There are no bars when playing a single stream or PiP.
> 
> I believe in this scenario one of the streamers(in the middle of smaller ones) had their game in some weird resolution, which resulted in letterboxing. I realised this after posting, but other streams were just fine.

Only in this letter box scenario there issue happens?

Or does also buyout is all are 16by9?

**Comment by fgl27** [comment]
> > if you enabled the below settings, does it help?
> > ![image](https://user-images.githubusercontent.com/13755892/284447213-b61ebfc0-ca91-46c2-98c1-ed299629093b.png)
> 
> Yes, this fixes the issue. It also introduces playback and interface slowdowns, is that normal?

Yes it consumes more resource but for some devices is the only option.

**Comment by MightyCrusier** [comment]
In that case, everything is working as intended. Thanks for the help!

**Comment by MightyCrusier** [comment]
> Only in this letter box scenario there issue happens?
> 
> Or does also bugout if all are 16by9?

The letterbox only appeared on that one stream, rest of them were displayed correctly. Assumed it was streamer's fault.
