### ISSUE TITLE
Stream does not resume correctly after certain ads

### ISSUE THREAD

**Issue by jazha** [fgl27/SmartTwitchTV#194]
**Describe the bug**
App fails to resume stream after certain ads.

**To Reproduce**
1. Go to any live stream
2. Watch until specific ads appear
3. Ad "crashes/stops" after 20-30sec and stream is unable to resume
4. I have to force close app, and pray to get a different ad when resuming stream

**Expected behavior**
Expect stream to resume when ads finish or stops

 
 **Device:**
 - TV Manufacture Device: Samsung Q9F 65"
 - Os version, unknown, dont know how to check

**Additional context**
- The issue seems to be specific to only certain ads, these days it is the ad with the coca cola santa drinking pepsi max that crashes every single time.

**Comment by fgl27** [comment]
For Samsung issue go to the Samsung repo, this is Android only 

There is already an issue for this

https://github.com/fgl27/smarttv-twitch/issues/277

**Comment by jazha** [comment]
Thank you, I missed the other repo completely!
