### ISSUE TITLE
More playback speed options

### ISSUE THREAD

**Issue by Js41637** [fgl27/SmartTwitchTV#195]
Could we support more playback speed options when watching vods such as in increments of 0.5?

At the moment you can only change the speed in 0.25 increments such as `1` `1.25` `1.5`. There is quite a big difference between 1 and 1.25 and I think some smaller options would be nice such as 1.05, 1.1, 1.15, etc. 

I personally watch a lot of vods on youtube at 1.05 or 1.2 and would really like this option in this app as well.

I looked at the code and you just have an array like this 
```
values: [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]
```

I think it could be worth just changing them to support increments of 0.5, it allows more flexability without really any downside except some values might now require more clicks to get to.

You could also just add some 0.5 increments around the start such as:
```
[0.25, 0.5, 0.75, 1, 1.05, 1.1, 1.15, 1.2, 1.25, 1.5, 1.75, 2]
```

I also considered maybe it could just be an option in settings to allow more values so someone could opt into using the 0.5 increments if they wish though it maybe feels a little unnessecary.

The choices are basically:

1. do nothing
2. update the array to just use increments of 0.5
3. update the array to just use increments of 0.5 but only a few around 1 (the example above)
4. add an option to settings to allow increments of 0.5 so its opt in and doesn't change existing behavior for those who don't want it

I'm happy to submit a PR with the required changes but I wanted to asked first what you think and what option you want to go with. Though I'm assuming the only changes required would be editing that array and possibly updating the settings page.

**Comment by fgl27** [comment]
sure you can mod this line and push a change to the repo

https://github.com/fgl27/SmartTwitchTV/blob/012693be4d95b4a9ae2492784dbfc9e029bb7096/app/specific/PlayEtc.js#L2263

and I will test and push an update
