### ISSUE TITLE
When selecting live channel, says channel is offline

### ISSUE THREAD

**Issue by lrgg** [fgl27/SmartTwitchTV#2]
**Describe the bug**
If you select a live channel, it says a short time "unable to get stream issue". Stream doesn't load and displays "channels has ended".

**To Reproduce**
1. Select any channel in your user follow list

**Expected behavior**
Stream of channel would start

**Operation system (if is a installation problem):**
Samsung Smart Tv

**Comment by fgl27** [comment]
I will push a new app to play to solve this... will take 1h or more to the app be visible there...
I let you know.

**Comment by lrgg** [comment]
How do I update the app? My app got automatically updated...

**Comment by fgl27** [comment]
this guit hub is for the play store app, the Android TV app.

are you sing Android TV?

**Comment by lrgg** [comment]
I am using a SAMSUNG Smart TV. I think it uses Tizen. I installed it with the Tizen Studio with your other guide.

**Comment by fgl27** [comment]
read here
https://github.com/fgl27/smarttv-twitch/issues/68

is solved alredy.

**Comment by lrgg** [comment]
Ok sorry I didn't read well. I found the Samsung TV repo. Closing this.

**Comment by remsrems11** [comment]
I currently have this issue for the last few hours on my Samsung TV, and also on my mibox which is an Android TV device.

**Comment by fgl27** [comment]
I already push a new apk to store and fix both Samsung and Android app
