### ISSUE TITLE
VODs not loading

### ISSUE THREAD

**Issue by NightHammer1000** [fgl27/SmartTwitchTV#201]
**Describe the bug**
Every VOD i try to watch failes with:
"Preview faild to Load: VOD unreachable, this VOD may have been deleted."
And clicking the VOD to watch it gets me "Unable to get Video Link"

**To Reproduce**
1. Go to any VOD
2. You see the First error.
3. Try to watch it.
4. You get the second one

**Expected behavior**
VOD should play

**Screenshots**
 
 **Device:**
 - STRONG LEAP-S3
 - Google TV (Android 11)

**Comment by Vlangusy** [comment]
For me too.

**Comment by Vlangusy** [comment]
It looks like Twitch itself is having problems though.

**Comment by fgl27** [comment]
Fine for me

**Comment by NightHammer1000** [comment]
Yeah. Working again
