### ISSUE TITLE
[Feature request] Match Frame Rate

### ISSUE THREAD

**Issue by OdinIsLord** [fgl27/SmartTwitchTV#203]
Hi, I use the Nvidia Shield Pro with your already fantastic app, however like in Kodi, having the option to enable "Match Frame Rate (MFR)" in player related settings to achieve buttery smooth playback depending on the content' fps would be great.

**Comment by fgl27** [comment]
most of Twitch is 60 or 30 keep the device at 30 60 or 120 and you will be fine.

is a feature that can be added I will not.

open source anyone can
