### ISSUE TITLE
Select multiple languages

### ISSUE THREAD

**Issue by LordBoos** [fgl27/SmartTwitchTV#21]
**Please describe the feature.**
I'd like to select more stream languages than 1 or all.

**Additional context or samples**
Eq. I want to see Czech, Slovak and English streams only. Right now I can only select "All languages" or 1 language.

**Comment by fgl27** [comment]
> Well you could call the API multiple times for each selected language and then merge the results to one list.

Is not simple as explain in plain text, I don't wanna change the app to do that.
