### ISSUE TITLE
Player Error code 2001

### ISSUE THREAD

**Issue by akejijia95** [fgl27/SmartTwitchTV#214]
When I try to watch any vods from any streamer the app show the text "Player unable to play due to player error Error code:2001"
 
 **Device:**
 - Smart TV TCL 50C647
 - Os version Android TV 11

**Additional context**
Error was showing sometimes after previous update, and now after last update it shows all the time.
Error happens on WiFi and on cable internet.
Live streams and clips works fine. Original Twitch app for Smart TV works fine. Watching from browser on Desktop PC and TV on WiFi and cable internet works fine. Tried installing this app on Android phone and watch on wifi - same error, but when I turn off WiFi and turn on the mobile internet it works. Same with twitch app on phone - vods only working on mobile internet. What interesting is that I can start watching vods on mobile internet and when it starts playing turn off mobile internet and turn on WiFi then it keeps playing just fine.

**Comment by fgl27** [comment]
This is a internet related error 

https://github.com/fgl27/ExoPlayer/blob/eb6f4b361ac7e4b3a6de821bded53f6e39562103/library/common/src/main/java/com/google/android/exoplayer2/PlaybackException.java#L140

The issue in in your local network. 

I have no idea what is, try to review all devices you network has one is causing it

**Comment by akejijia95** [comment]
The issue was not in network, I even bought new router to replace the old one(it broke). I was avoiding the problem by using vpn for month, but today I noticed that problem was gone. Seems like people on the internet was right and it was something wrong on the twitch end.

**Comment by fgl27** [comment]
Yes a network error doesn't mean an device issue.

Is best to test on a different network first.

Sorry if I miss that, but testing on a mobile network by sharing (personal hotspot) is an option.

Another is to test an different device, you can install this on an Android phone downloading the APK 

https://github.com/fgl27/SmartTwitchTV/releases

Any way I assume you manage to figure those out by yourself.

In the end was just Twitch miss using some geo location feature to block you. 

Good that is working, thanks for sharing the update
