### ISSUE TITLE
[Feature Request] Completely hide blocked channels

### ISSUE THREAD

**Issue by lextra2** [fgl27/SmartTwitchTV#215]
I need an option or a way to hide livestreams of users I've blocked from ever being shown anywhere in the app.

**Comment by fgl27** [comment]
What do you mean? 

Once you blocked that is it they gone.

But if you block a followed channel they show, so don't just block them if that is the case unfollow too.

**Comment by lextra2** [comment]
Then my twitch blocklist isn't being imported.
![Screenshot_2024-04-08-16-53-07-186_com kiwibrowser browser-edit](https://github.com/fgl27/SmartTwitchTV/assets/20690384/e9de3ff9-5bc0-48de-bce0-bc5c0cbdc91f)

_Blocked_ is empty in the app.

**Comment by fgl27** [comment]
Current blocked implementation is on the app, the app can't retrieve yours blocked channels from the site. 

Technically is possible, but the possibility of importing from the site came after I have made a building implementation. 

So some day I will update it. 

For now block the channel in the app too.

Just hold left above a thumbnail and click enter on block Chanel, you can block channels and games.

**Comment by lextra2** [comment]
Ohh, in-app blocking. Yeah. That works. Thanks.

**Comment by fgl27** [comment]
I let you know here the day the app is syncing with the web site.
