### ISSUE TITLE
Follow Raid

### ISSUE THREAD

**Issue by MagFlux** [fgl27/SmartTwitchTV#218]
Hello,

Love the app and appreciate all the effort you’ve put into this. 

Apologies if I’m missing the setting but is there a way to have the channel being viewed auto switch to the destination channel of a raid at the end of a stream like it does on the web?

Thanks!

**Comment by fgl27** [comment]
#185 is open.

Didn't had time to work on this when twitch retired the old host option.

will keep only one issue open for this.
