### ISSUE TITLE
live playback issue on LG smart TV (webOS)

### ISSUE THREAD

**Issue by bel57** [fgl27/SmartTwitchTV#219]
Hello,

**Current issue**
I'm having an issue with SmartTwitchTV on my smart TV. Everything is running "fine" except livestreams. I can see the thumbnails, and when I click on a stream, it's just a frozen frame of the thumbnail, nothing playing. How to get it unstuck? Is there a particular setting I should tweak? Btw clips and VOD feeds are playing as expected.
I'm using the website with the builtin browser.

**To Reproduce**
Join a livestream. Nothing happens, just a still frame. Chat however is scrolling as usual

**Expected behavior**
Working playback

**Screenshots**
I don't. The issue is pretty self explanatory
 
 **Device:**
- LG 27LQ625S-PU
- FW: 03.30.73
- Magic Remote

I just found out recently about this tool as an alternative to the horrible official app.
Thanks!

**Comment by fgl27** [comment]
When you use it on an web browser the app plays lives and vids using Twitch embedded player. 

The only thing to enable is the twitch player, set below to YES

![Screenshot_2024-06-05-09-51-49-26_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/fgl27/SmartTwitchTV/assets/13755892/1557e846-a59b-43ec-965e-856cbe66cacb)

If it works for vod is odd that doesn't for lives.

The clip player is different in an building browser player.

I can't test this I don't have an LG or a.way to debug on an LG.

This is something between the twitch player and that TV os not much that can be done.

Try a different browser if one is available.

**Comment by bel57** [comment]
Thanks. I'm not sure there are other browsers except default one.
Gave it a try again and it's working now after clearing the browser data and double checking all settings.
I assume compared to the Android version I have on my box, the web app can't use the builtin player for live streams, that's why it's loading twitch web?

**Comment by fgl27** [comment]
Yes the player is in the APK for the Android app.

Is the only way to extract the most performance of the device and do all you can do with multiple player running at the same time.

**Comment by bel57** [comment]
I see. Unfortunately the web player video quality is kinda blurry, buffering and frame rate not super smooth. Might be a performance issue with my TV, I'll have to switch back to the official app. However I'll keep using STTV on my Android box. Thanks!

**Comment by fgl27** [comment]
That is because the browser implantation on the TV is very bad, is technically an app that emulates a browser. 

On nione Android TVs I just use an Android box for YouTube and twitch as the official apps. Just suck and Android allows you to easily use a third party app.
