### ISSUE TITLE
Thumbnail preview volume does not change even if changed in settings.

### ISSUE THREAD

**Issue by spamitinmy** [fgl27/SmartTwitchTV#22]
**Describe the bug**
The volume of the thumbnail preview remains at 100% even if you changed it to lower in the settings.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Preview thumbnail player settings'
3. Scroll down to 'Preview Volume'
4. Change percentage to something low, ie. 20%
5. Keep the main player volume higher than the preview volume, ie 75%
6. Watch a channel
7. Open up the preview thumbnails and hover to a different channel.
8. The preview channel seems to be at 100% volume, rather than 20% volume.

**Expected behavior**
When previewing a channel while watching from the main player, the preview player should be quieter than the main player.

 **Device:**
 - TV Manufacture Device: Nvidia Shield
 - Shield experience v8.2

**Comment by fgl27** [comment]
Thank you... Was only working for VOD previews now is OK for all
A app will be available later on play store.
