### ISSUE TITLE
Crashing when opening stream after latest update

### ISSUE THREAD

**Issue by s1p2a3m** [fgl27/SmartTwitchTV#223]
**Describe the bug**
Everytime I open a stream after the latest Google Play update, the app just crashes.
I can see the chat connect and open, but right before the video starts it crashes.

**To Reproduce**
1. Open any stream
 
**Device:** _(taken from about page)_
Apk: 3.0.365
Web: August 2024
Webview: 127.0.6533.64
Device: Sony - Bravia VH1
Sdk: 29

**Additional context**
Tried changing codecs, whatever setting I could think of that could cause a crash, but nothing worked.
Also checked for webview update, restarted the TV.

**Comment by s1p2a3m** [comment]
Very weird, was trying VODs to see if they were working, which they are, then tried a live stream while it was playing (not sure if it mattered) and afterwards live streams work (even after closing the app).

¯\_(ツ)_/¯

**Comment by fgl27** [comment]
I notice the problem fix it after a few minutes, all OK for me

all OK now? please confirm

**Comment by fgl27** [comment]
only then? you have to open a vod everitime you open the app, or else you can't play lives?

I just wanna to know if, when the app is closed, you open the app and it plays anything witout any workaround?

example you open a live after just starting the app and it works

**Comment by CristianGrecu** [comment]
I have a Bravia VH2, mine is updating right now, will post an update if it breaks the app in any way.

**Comment by CristianGrecu** [comment]
Update: my app works perfectly.

**Comment by fgl27** [comment]
> Very weird, was trying VODs to see if they were working, which they are, then tried a live stream while it was playing (not sure if it mattered) and afterwards live streams work **(even after closing the app).**
> 
> `¯\_(ツ)_/¯`



> It works after opening a VOD as I wrote above, not sure what you want to confirm.



> only then? Do you have to open a vod every time you open the app, or else you can't play Lives?
> 
> I just want to know if, when the app is closed, you open the app and it plays anything without any workaround?
> 
> For example, you open a live after just starting the app and it works

I asked you to confirm something you alredy did confirm, thanks you! all OK

**Comment by s1p2a3m** [comment]
After opening a VOD it fixed itself, I don't have to do anything else after opening.

**Comment by fgl27** [comment]
> After opening a VOD it fixed itself, I don't have to do anything else after opening.

wasn't that, that fix it, I pushed a silent fix. the app receives whenever you open it.

the problem of the live also affected VODs, only thing not affected was clips.

this app auto updates it self silently, not everithibng but a few parts it can do it.

**Comment by s1p2a3m** [comment]
Oh ok :D
