### ISSUE TITLE
Main Menu > Live will stop scrolling with too many channels blocked

### ISSUE THREAD

**Issue by lextra2** [fgl27/SmartTwitchTV#228]
**Describe the bug**
I have about 2000 Channels blocked.
Now when I go to Main Menu > Live section, only the first 6 Channels will show. Scrolling becomes impossible. This doesn't always happen but about 80% of the time.

**To Reproduce**
1. Block hundreds of channels
2. Restart the app
3. Go to Main Menu > Live
4. Try to scroll

**Expected behavior**
I can scroll

**Operation**
 - OS: Fire TV Stick 4K
 - Version: Newest

**Additional context**
Maybe the issue is related to the scrolling animation, or maybe increase the amount of channels that are loaded, so it naturally forces you to scroll. Going from 6 to 12 channels loading per scrolling step could fix it.

**Comment by fgl27** [comment]
What do you wanna me to? do you blocked everything that there is to show

**Comment by lextra2** [comment]
Haha
It might look like that but not really.
There are still thousands of live channels, which I haven't blocked.

Like I said, maybe the issue is with the amount of preloaded channels per scroll "section".
If you could add an option in the settings to increase the amount of channels loaded I think this issue would be fixed.

**Comment by fgl27** [comment]
Other sections load 100 per API request, you see less but the app has the data to fill up the section as it gets consumed by blocked...

I'll try something when I do. I'll let you know.

**Comment by lextra2** [comment]
> That section supports 30 channels only, hardcoded API limitation.

Oh wow. Pretty stupid of Twitch

> I'll try something when I do. I'll let you know.

👍

**Comment by fgl27** [comment]
They made the API for their use only...

I made some changes not yet done, once done I'll let you know to test them...

**Comment by fgl27** [comment]
This is resolved test let me know the result

**Comment by lextra2** [comment]
When I try to update I get an error saying
"The package conflicts with an existing package by the same name"

I think I gotta manually delete the app and install the newest APK?
But then I'd lose my blocklist and settings.

Is there any better way to fix this?

**Comment by lextra2** [comment]
No, it would give me the error I posted above.

But I fixed it by deleting the app and installing the newest apk.
I didn't know it had a backup function.

Everything works now. Live channels load now.
Thank you very much for the quick fix.

**Comment by fgl27** [comment]
you don't need to update the app, just let it update itself, it will tell you when is needed

the backup only work on som Android version,

**Comment by fgl27** [comment]
Also, I advise you to uninstall the app you downloaded and install it from the Play Store.

the update isn't on the APK.

**Comment by fgl27** [comment]
The auto update is there for.years, so wherever app you was was ok.

Have no idea why the errors then

**Comment by fgl27** [comment]
Are you using the app fron release?

https://github.com/fgl27/SmartTwitchTV/releases

Because those error are there only if the APK being installed is from.a diff source 

I expect the one from release to have a proper icon and installing from the same source must not give errors 

Maybe the icon shows after a device reboot

**Comment by lextra2** [comment]
> Are you using the app fron release?

Yes

> Maybe the icon shows after a device reboot

Nope. doesn't fix it. Even in the directory explorer "Cx File Explorer" the icon is the green android

But viewing the apk on my tablet with the same file explorer shows the correct icon.

**Comment by fgl27** [comment]
I pushed an app update let me know if it updates itself OK, you may need to give the app install permission

**Comment by lextra2** [comment]
Yup. Works without trouble.

**Comment by fgl27** [comment]
OK great.

the icon is bugged, right?

didn't have time to address that is minor so will some day

**Comment by lextra2** [comment]
>the icon is bugged, right?

yes. as you can see in this picture
![IMG_20241026_133836](https://github.com/user-attachments/assets/a50e9d89-3d16-4b84-a41c-bddbdcd46542)
