### ISSUE TITLE
Sidepanel doesn't work

### ISSUE THREAD

**Issue by Silergo** [fgl27/SmartTwitchTV#23]
After open sidepanel with favored online channel you can't collapse it with forward button. Also choosing options there (User Menu, Live, Featured, Games, etc) doesn't do anything. It's collapses and doesn't expand again.

**Comment by fgl27** [comment]
I can't replicate that, you can open the app page here

https://fgl27.github.io/SmartTwitchTV/release/index.min.html

Use the keyboard d-pad (arrow keys) + enter to navigate
For return key use ESC or Backspace keys

Maybe is something very specific that causes it... can you find what exactly causes?

**Comment by fgl27** [comment]
It fails if you don't add a use I get it now will fix it.

**Comment by fgl27** [comment]
Done close the app by holding the return key after all will be OK.

**Comment by Silergo** [comment]
> 
> 
> I can't replicate that, you can open the app page here
> 
> https://fgl27.github.io/SmartTwitchTV/release/index.min.html
> 
> Use the keyboard d-pad (arrow keys) + enter to navigate
> For return key use ESC or Backspace keys
> 
> Maybe is something very specific that causes it... can you find what exactly causes?

It doesn't work on Android TV with TV Remote.

**Comment by fgl27** [comment]
> > I can't replicate that, you can open the app page here
> > https://fgl27.github.io/SmartTwitchTV/release/index.min.html
> > Use the keyboard d-pad (arrow keys) + enter to navigate
> > For return key use ESC or Backspace keys
> > Maybe is something very specific that causes it... can you find what exactly causes?
> 
> It doesn't work on Android TV with TV Remote.

That link is for testing on a computer. On android you can use the app

**Comment by Silergo** [comment]
> 
> 
> > > I can't replicate that, you can open the app page here
> > > https://fgl27.github.io/SmartTwitchTV/release/index.min.html
> > > Use the keyboard d-pad (arrow keys) + enter to navigate
> > > For return key use ESC or Backspace keys
> > > Maybe is something very specific that causes it... can you find what exactly causes?
> > 
> > 
> > It doesn't work on Android TV with TV Remote.
> 
> That link is for testing on a computer. On android you can use the app

That what I'am trying to say. Sidepanel on your android app downloaded through Google Play doesn't work on AndroidTV with TV Remote.

**Comment by fgl27** [comment]
It does. I already fix it. read the issue in the web page see all my post

**Comment by Silergo** [comment]
> 
> 
> It does. I already fix it. read the issue in the web page see all my post

Wow, really fixed, sorry. Without update the app through market. So it somehow rely on web server?

**Comment by fgl27** [comment]
Part is. The UI is all on a web server, makes easier to update.

**Comment by Silergo** [comment]
> 
> 
> Part is. The UI is all on a web server, makes easier to update.

Hmm, so if server is down/closed the app won't work normally?

**Comment by fgl27** [comment]
Yes if the served is down the app will not.open.
