### ISSUE TITLE
Can't block channels in Categories with too many Streamers?

### ISSUE THREAD

**Issue by lextra2** [fgl27/SmartTwitchTV#231]
I can no longer block channels in some categories.

1. Go to Black Ops 6
2. Block any channel at the top
3. Channel disappears
4. Refresh the page
5. Channel reappears

Doesn't happen in categories with less streamers (under 1000, I guess)

**Comment by fgl27** [comment]
can't replicate that, maybe you blocked the game?

**Comment by lextra2** [comment]
Please see this video
https://streamable.com/h58czu

>maybe you blocked the game

This doesn't change anything

**Comment by fgl27** [comment]
can you record in a way I can see the whole screen?

**Comment by fgl27** [comment]
You probably have this set to YES 

![image](https://github.com/user-attachments/assets/f6451b09-c18f-4e66-961d-72ab6b461c63)

But I can't see it

**Comment by fgl27** [comment]
When show blocked is set to yes after a refresh that will happen

![image](https://github.com/user-attachments/assets/f1fbbc58-d099-4a84-a82a-ba691f34e219)

**Comment by lextra2** [comment]
Oh wow I'm stupid.
Yeah that was it 🤣
Thanks!

**Comment by fgl27** [comment]
Don't worry, happens.

I will add some warnings on the screen for those scenarios to avoid any related issues.
