### ISSUE TITLE
Clicking Up to bring up Multi View on button of screen the LIVE Follow Streamers List Will not Update when you hold on to the Up Button for a few Seconds to refresh the LIVE Follow Streamers List it just Keeps Spinning on the button of the Screen not refresh the LIVE Follow Streamers List it is Happening on Both Fire TV OS 7 & Fire TV OS 8 and is Happening on Google TV OS 12.

### ISSUE THREAD

**Issue by Yug91st** [fgl27/SmartTwitchTV#235]
**Describe the bug**

This Problem Started on Wednesday November 13, 2024. Clicking Up to bring up Multi View on button of screen the LIVE Follow Streamers List Will not Update when you hold on to the Up Button for a few Seconds to refresh the LIVE Follow Streamers List it just Keeps Spinning on the button of the Screen not refresh the LIVE Follow Streamers List it is Happening on Both Fire TV OS 7 & Fire TV OS 8 and is Happening on Google TV OS 12 Tried Reinstalling the App but the Problem is still Happening on the App after Reinstalling the App. Pretty Please Can You Help Fix this Problem With the App. It Would Be Greatly Appreciated. Thank You Very Much.

**To Reproduce**
4. See error something doesn't work

Clicking Up to bring up Multi View on button of screen the LIVE Follow Streamers List Will not Update when you hold on to the Up Button for a few Seconds to refresh the LIVE Follow Streamers List it just Keeps Spinning on the button of the Screen not refresh the LIVE Follow Streamers List

**Expected behavior**

Clicking Up to bring up Multi View on button of screen the LIVE Follow Streamers List Will not Update when you hold on to the Up Button for a few Seconds to refresh the LIVE Follow Streamers List it just Keeps Spinning on the button of the Screen not refresh the LIVE Follow Streamers List

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield, Xiaomi Mi box I II III IV, etc...
 - Os version [e.g. Android 9, 10 etc...]

it is Happening on Both Fire TV OS 7 & Fire TV OS 8 and is Happening on Google TV OS 12 Tried Reinstalling the App but the Problem is still Happening on the App after Reinstalling the App

**Additional context**

**Comment by fgl27** [comment]
Not an app problem have not made any changes in the past two weeks, works as expected to me.

try to reboot your device or check the remote seems a device/remote issue.

as this is happening to all of your devices maybe is an app you use to change how controller input works so try to disable and uninstall any app you use to change how keys behave for example.

**Comment by Yug91st** [comment]
I Have No Button Remapper App programmed to any Keys on Any Remote I Use. I Am Using SmartTwitchTV Version 371 3.0.371 Downloaded it from Your GifHub Website APK Download Page and All My Units I Use have the Downloaded APK Version 371 3.0.371 Downloaded it from Your GifHub Website APK Download Page. The Main Unit I Use is the Fire Tv Stick 4k Max 2nd Gen Fire OS 8 and I have Backup units that are unplugged and waiting to be used if something goes wrong with my main Unit My Backup Units are Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and the Other Backup Unit is Chromecast with Google TV 4K Google TV OS 12. On Wednesday November 13, 2024 on the Fire Tv Stick 4k Max 2nd Gen Fire OS 8 the App was working great for the Last Year and a half I been using the App I Would click up on the remote once to pull up the Multi View Menu on the button of the screen to get to My LIVE Favorite Followers List to choose from and when I Hold on to the UP Button for One Second and took my finger off the Button to Refresh the My LIVE Favorite Followers List it would Always Refresh the List for Me to choose somebody from My LIVE Favorite Followers List to Put Somebody on Fullscreen or put them in the Picture In Picture anywhere on the screen But the Problem Started on Wednesday Night November 13, 2024 I had the App Open I Would click up on the remote once to pull up the Multi View Menu on the button of the screen to get to My LIVE Favorite Followers List to choose from but it would only keep Show a White Spinning Circle that White Spinning Circle would Refresh My LIVE Favorite Followers List to choose from on the Multi View Menu on the button of the screen but the White Spinning Circle will keep spinning will not Refresh My LIVE Favorite Followers List at all. But when I click up on the remote once to pull up the Multi View Menu on the button of the screen and click up to the 2 List that are not Follower List I Can See Both List and I Can Hold on to the UP Button for One Second and took my finger off the Button to Refresh the 2 not Follower List. I Tried Fixing This Problem on My Fire Tv Stick 4k Max 2nd Gen Fire OS 8 I Took OS 8 Updates and Reboot and Restarted the Stick and Unstalled and Reinstalled SmartTwitchTV Version 371 3.0.371 Downloaded it from Your GifHub Website APK Download Page and Still did not Fix the White Spinning Circle will keep spinning will not Refresh My LIVE Favorite Followers List at all on the Multi View List that can be pulled up at the button of the screen. I also Checked My Backup Units That Were Unplugged My Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and the Other Backup Unit is Chromecast with Google TV 4K Google TV OS 12 both Units have SmartTwitchTV Version 371 3.0.371 Downloaded it from Your GifHub Website APK Download Page. I Plugged each Unit in Separately to See if the Problem was Happening on the SmartTwitchTV APK Version 371 3.0.371 on each Unit and the Problem was Happening on Both of My Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and the Other Backup Unit is Chromecast with Google TV 4K Google TV OS 12. I Tried to Fix the Problem by Updating the Operating System and Reboot and Restarting each Unit and each Unit Uninstall and Reinstall the SmartTwitchTV APK Version 371 3.0.371. But it Did Not Fix the Problem White Spinning Circle will keep spinning will not Refresh My LIVE Favorite Followers List at all on the Multi View List that can be pulled up at the button of the screen. These Problem is on the SmartTwitchTV APK Version 371 3.0.371 on All 3 of My Units My Fire Tv Stick 4k Max 2nd Gen Fire OS 8 and My unplugged and waiting to be used if something goes wrong with my main Unit My Backup Units are Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and the Other Backup Unit is Chromecast with Google TV 4K Google TV OS 12. Pretty Please Can You Help Fix this Problem With the App. It Would Be Greatly Appreciated. Thank You Very Much.

**Comment by fgl27** [comment]
are you good?

you wrote a book that makes no sense I'm not reading it all.

**Comment by fgl27** [comment]
All my test I can't reproduce the problem if you have a way to do so let me know

you can open the app here

https://fgl27.github.io/SmartTwitchTV/release/index.html

open the app and try you will see it works, try a clip as the clip UI is the same as the apk.

maybe is a random setting that causes issues, try to change settings if you find one that does let me know

try not to write a book as I will not read it.

**Comment by Yug91st** [comment]
Simplified I Did Not Change any Settings on TV App Version on Fire TV Stick 4K Max 2nd gen and Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and Chromecast with Google TV 4K Google TV OS 12. I Did Not Remap any buttons on any of my Remotes. Last Night Problem just Started by itself on the TV App on 1 Device I Had Plugged In. Pretty Please Help Fix this I Apologize I am Handcapped and is hard for me to See And type I Wanted You To Know Exactly what was Happening so It Would help you fix it. I Am Very Sorry I Apologize for All the Words.

**Comment by fgl27** [comment]
so that one device and only in that one device do you have the issue?

if yes can you try a different device?

can you try a different remote control?

does the problem show when changing devices? if yes must be a configuration that you do on both devices like a device setting or app

if not the problem is on the device and I have no idea what is.

If after changing the controller the problem is gone the problem is on the remote

that is all I can do, I can't reproduce the issue what points that the issue is on the device not the app.

**Comment by fgl27** [comment]
btw you can also refresh by using the number 2 key... in case your remote has numbers keys

**Comment by Yug91st** [comment]
Last message I told You the Devices the problems on TV App Version on Fire TV Stick 4K Max 2nd gen and Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and Chromecast with Google TV 4K Google TV OS 12 there is no number 2 button on any of my Remotes I Just Tried uninstalling TV APK Version 371 3.0.371 and I Installed Downgraded to the Last Version In October TV APK Version 369 3.0.369 The Problem That Started Last Night is still Happening on the Old Last Months Version I Just Installed. I Am Very Sorry I Apologize for All the Words.

**Comment by fgl27** [comment]
No worries is all good I understand why so many words...

this is something on the device, revise the controller, if that doesn't help revise the device and see what can cause the issue, maybe an unknown setting changed after some device update.

**Comment by Yug91st** [comment]
Problem started Last Night On Main Plugged In Device I Use Fire TV Stick 4K Max 2nd gen I Last Updated the Operating OS on the device 2 Weeks Ago and there was no problem until Last Night when the problem Started on the SmarttwitchTV TV App. To fix the problem tried Updating Operating OS and Reboot and Restart device and Uninstall and Reinstall the TV App Did not Fix the Problem.

**Comment by Yug91st** [comment]
Last Night I also Tried my Unplugged Devices that have not had any Operating System OS Updates for Two Months My Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and Chromecast with Google TV 4K Google TV OS 12 I Plugged in each one Separately I Only Launched the SmarttwitchTV TV App to See if the Problem was Happening on the TV App and the problem was Happening on both TV Apps On Both Devices.

**Comment by Yug91st** [comment]
I Recorded a Small video 9 mb to Show what's happening on the TV App but your GitHub page keeps telling me it needs to 10 mb it Will not let me post on the message page is there and other way to get this video to you.

**Comment by fgl27** [comment]
You can email fglfgl27@gmail.com or YouTube it and share the link

**Comment by fgl27** [comment]
Is just up key that has holding issues? 

OK or enter key is used to refresh when outside of the player 

Does that works?

You can also hold Left for thumbnails options outside the player

Any issues there?

**Comment by Yug91st** [comment]
Something Weird Happened tonight 24 Hours after this Problem Started One Minute Before You Sent your Last Help Message to Me I went and opened up the SmarttwitchTV TV App on My Fire TV Stick 4K Max 2nd Gen Fire TV OS 8 I wanted to See if the White Spinning Circle was still not Refresh My LIVE Favorite Followers List to choose from on the Multi View Menu on the button of the screen Now the Weird Thing 24 Hours Later I Pushed the Up Button One Time and it Finally Refreshed My LIVE Favorite Followers List to choose from on the Multi View Menu on the button of the screen and it Finally let me Hold down the UP Button for One Second to Refresh My LIVE Favorite Followers List on Multi View Menu on Button of Screen.

**Comment by Yug91st** [comment]
Also the weird Thing is I went and Checked My Unplugged Fire TV Stick 4K Max 1st Gen Fire TV OS 7 and Chromecast with Google TV 4K Google TV OS 12 I Plugged in each one Separately I Only Launched the SmarttwitchTV TV App to See if the Problem was Happening on the TV App and Weirdly I Pushed the Up Button One Time and it Finally Refreshed My LIVE Favorite Followers List to choose from on the Multi View Menu on the button of the screen and it Finally let me Hold down the UP Button for One Second to Refresh My LIVE Favorite Followers List on Multi View Menu on Button of Screen. Weirdly it's Fix 24 Hours Later on both TV Apps On Both Devices.

**Comment by Yug91st** [comment]
I Do Not Know 24 Hours Later How This got Fixed but I Hope this Refresh Problem on the My LIVE Favorite Followers List to choose from on the Multi View Menu on the button of the Screen Does Not have this Problem Again in the Future on the SmarttwitchTV TV App. I Am Very Sorry I Apologize for All the Words and Any Problems that I May have Caused for you. Also Thank You for your Suggestion in your last Message about Settings Customize content,. sorting, auto refresh,. timeout and related Set... Auto refresh timeout To 10 minutes This Might Help in the Future if this Problem Comes back Again. I Greatly Appreciate Your Help with this Problem. Thank You Very Much.

**Comment by fgl27** [comment]
OK no worries glad is all good.

Sometimes.devices receive silent updates how.

If need let me know.
