### ISSUE TITLE
RUssian language has disappeared from the app

### ISSUE THREAD

**Issue by script4u** [fgl27/SmartTwitchTV#236]
**Describe what you need.**
It seems that Russian language has disappeared from the app, why did this happen? Will it be restored?

**Additional context**
Related PR:
https://github.com/fgl27/SmartTwitchTV/commit/94fd628a9b41f5c1f9816bc35df048712af1c5e3

**Comment by fgl27** [comment]
I remove it is no longer up to date

**Comment by script4u** [comment]
But why?

**Comment by script4u** [comment]
> I remove it is no longer up to date
But why?

**Comment by script4u** [comment]
If I submit PR with RU translation according to the instruction, will it be returned?
https://github.com/fgl27/SmartTwitchTV?tab=readme-ov-file#how-to-translate-and-test

**Comment by script4u** [comment]
Here is the updated ru_Ru.js file with the missing variables from en_US.js
[ru_Ru.js.zip](https://github.com/user-attachments/files/17823074/ru_Ru.js.zip)

**Comment by fgl27** [comment]
can you review, using the below?

https://fgl27.github.io/SmartTwitchTV/app/index.html

**Comment by fgl27** [comment]
I fix that and pushed all changes to the app, close the app reopen and the lang must be there working
