### ISSUE TITLE
"Single return press" does not work after broadcast ends.

### ISSUE THREAD

**Issue by moninahh** [fgl27/SmartTwitchTV#238]
**Describe the bug**
"_Single return press_" does not work after broadcast ends.

**To Reproduce**

1. Set "_Single return press_" in the settings.
2. Broadcast ends.
3. The countdown to automatic out begins.
4. Press single back.
5. Requires pressing again to exit.

**Expected behavior**
Exit by single pressing of the "Back" button.

 **Device:**
 - TV Manufacture Device: SONY TV
 - Os version: Android 9

**Comment by fgl27** [comment]
OK I'll take a look.

**Comment by fgl27** [comment]
Delay when? The same scenario when the stream ends. Happens when vod or.clips end?
