### ISSUE TITLE
Add zero-width/overlay emote support

### ISSUE THREAD

**Issue by JanitorialMess** [fgl27/SmartTwitchTV#242]
Currently, zero-width/overlay emotes display as regular emotes rather than overlaying on other emotes.
Examples of zero-width emotes can be found here: https://7tv.app/emotes?page=1&query=zerowidth&o=1

**Comment by fgl27** [comment]
I don't understand what this emote does where are the technical explanation and visual examples?

**Comment by fgl27** [comment]
I tried a few to see how it work, will check if possible

![{E47D5869-4D4C-4BDC-BFEA-5CEE2ADBF806}](https://github.com/user-attachments/assets/4fb29964-190e-4cb4-a6f4-8decf79b6815)

**Comment by fgl27** [comment]
that last commit is just for custom emotes it doesn't work with twich emotes yet, once it does I push to the app...

it looks like this for now

![image](https://github.com/user-attachments/assets/78cf298e-ed4c-41fc-a9c1-c2d15130a687)

**Comment by fgl27** [comment]
Thanks, I didn't know about the emojis issue. Will take at look at their implementation.

Any other emote provider other then 7tv is using zero-width/overlay emotes ?

**Comment by fgl27** [comment]
I pushed the changes adding the support for the 7tv emotes

I also included the changes for "[RFC](https://gist.github.com/Mm2PL/982c76964fe53f80fcf6b6963bba049f)"

If anything is not working as expected let me know.

Thanks!

**Comment by fgl27** [comment]
Thanks for the test

seems ok now

![image](https://github.com/user-attachments/assets/0f1045d5-b1e8-4ec2-8256-582fce77d05b)


test let me know if any other issues

**Comment by fgl27** [comment]
You can test by adding the same a few times... I did seems all good. Thanks for the help.

You can see on yours channel on this app? Or the twitch site?

I assume is a caching thing.

**Comment by fgl27** [comment]
Thank you!
