### ISSUE TITLE
Bro Cagaron con la actualización 

### ISSUE THREAD

**Issue by AndersonB3M** [fgl27/SmartTwitchTV#244]
Metieron una actualización y jodió la aplicación
![17346699625186781540298406465719](https://github.com/user-attachments/assets/60229cf1-89d7-4fd1-9214-284d5f8e6ab7)
, entra se queda cargando, ya formateé el televisor mire si era el internet y nada jodieron todo con esa actualización

**Comment by destiny08-lab** [comment]
same problem

**Comment by fgl27** [comment]
same as #243 will close this follow the other, please.

**Comment by fgl27** [comment]
Have you try the app right now and still doesn't work?

Even after you close and reopen the app?

**Comment by AndersonB3M** [comment]
> ¿Has probado la aplicación ahora mismo y aún no funciona?
> 
> ¿Incluso después de cerrar y volver a abrir la aplicación?

Estoy que mando todo a la mierda por qué no quiere coger la aplicación 

![17347079256921553149418890854367](https://github.com/user-attachments/assets/5e7bcbfb-76eb-4c9c-b0b6-b3e9a2985caa)
