### ISSUE TITLE
4-way multi stream gets confused with only 3 streams active

### ISSUE THREAD

**Issue by Auram** [fgl27/SmartTwitchTV#245]
**Describe the bug**
When I'm using the 4-stream view with only 3 streams sometimes after switching main stream it will get confused on which stream is which. It will swap chats around and end up having one be "undefined." Sometimes if you swap multiple times in quick succession it can fix itself. Doesn't happen ever with 4 streams. 

**To Reproduce**
Enter 4-stream multi view, select 3 streams, make one primary, swap quickly. 

**Expected behavior**
I expect them not to get confused with each other. 

**Screenshots**
n/a
 
 **Device:**
 NVIDIA Shield

**Comment by fgl27** [comment]
Will review this next day I have some time.

Thank you!

**Comment by fgl27** [comment]
The above fixes it, I push a update to the app, try it and let me know

**Comment by Auram** [comment]
Seems to work great now, thank you for the fast update! The app is really great, fixes every issue I had with S0undTV and other Twitch apps. Looking forward to the chat width setting and maybe some more customizable height sizes!
