### ISSUE TITLE
Shared chat cannot be disabled

### ISSUE THREAD

**Issue by lextra2** [fgl27/SmartTwitchTV#246]
I've disabled the shared chat under settings, but it doesn't work.

1. Disable shared chat under chat options
2. Go to Streamer JokerdTV
3. Observe how the chat is still shared

**Comment by fgl27** [comment]
For me works just fine

The goal is to filter out messages from diff chats 

That is working as expected

What is the problem for you?

**Comment by lextra2** [comment]
1. it still say shared chat
2. when I join a stream that uses a shared chat, it lists the connected streamers

**Comment by lextra2** [comment]
so maybe its just me being confused by that?

imho those two things should be hidden if shared chat is disabled to stop confusion.

**Comment by fgl27** [comment]
Sure the idea is to know is shared and just filter out msg

But I can remove the warnings

**Comment by lextra2** [comment]
> Sure the idea is to know is shared and just filter out msg

Oh ok, yeah that was what I was confused about.

>But I can remove the warnings

The warning is fine for people who have shared chat enabled.
Please only hide it if shared chat is disable

**Comment by fgl27** [comment]
I push some adjustments to avoid confusion, thanks for sharing the info

Now once you set disabled shared to YES it will not show the warning and remove the in-shared chat from the chat

**Comment by fgl27** [comment]
If you enabled shared and the chat is in shared mode, as soon as you enable the text and warning will pop

this must avoid any confusion...

**Comment by lextra2** [comment]
perfect
and thanks for the fast fix, as always ;)
