### ISSUE TITLE
Ads still play with subscribed account connected

### ISSUE THREAD

**Issue by dmitittt** [fgl27/SmartTwitchTV#25]
**Describe the bug**
Account with subs connected but ads still play on subscribed channels.

https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

65H8F AndroidTV 9

**Comment by fgl27** [comment]
Keep all ads related on the same place https://github.com/fgl27/SmartTwitchTV/issues/24 don't open a issue on the wrong repo or a duplicated one please
