### ISSUE TITLE
Player unable to play due to player error

### ISSUE THREAD

**Issue by dmitittt** [fgl27/SmartTwitchTV#26]
Whenever I back out of a stream it continues playing the audio, then it doesn't allow me to switch to any other stream or resume the current one without first force stopping and relaunching.

**To Reproduce**
1. Go play a stream
2. attempt to switch or return to main menu

**Expected behavior**
to switch between streams without resetting the app.

**Device:**
 - TV Model: 65H8F Hisense
 - Os version AndroidTV 9

**Additional context**

**Comment by fgl27** [comment]
I can't reproduce this.

Are you sure you are using latest app version? with is 3.0.272

Just check the about of the app.

**Comment by fgl27** [comment]
@dmitittt I move the issue t the correct repo, I also did to the other you open.
I particularly don't know if github inform you about that and you are lost not finding the issue, but I know that an mention forces a notification if you have set the proper email and etc related you must receive one now.

Let me know what I asked before, and if you notice the repo change of the issue before this?

**Comment by dmitittt** [comment]
https://streamable.com/iyogux

**Comment by fgl27** [comment]
I can't reproduce that, uninstall the app download a old version from here https://github.com/fgl27/SmartTwitchTV/releases
And let me know what is the newest version that works.

To downgrade a app you need always uninstall it first.

**Comment by fgl27** [comment]
Also show me the info from the about of the app. any version I just need the device info there

**Comment by fgl27** [comment]
I assume that the same problem will happen if you are playing a video and press the home key then try to go back to the app

test that let me know the result.

Also let me know if that happens to VOD and clips not just lives

**Comment by dmitittt** [comment]
happens to all playback, it was updated to the latest version and i just updated it again couple hours ago. im going to bed now but i appreciate this app nonetheless, i use it everyday. just annoying i have to force stop it whenever i want to switch channels and that i have to make my decisions fast because it autoplays streams from the thumbnails.
ill look for the about info page of the app tomorrow morning.

**Comment by fgl27** [comment]
> happens to all playback, it was updated to the latest version and i just updated it again couple hours ago. im going to bed now but i appreciate this app nonetheless, i use it everyday. just annoying i have to force stop it whenever i want to switch channels and that i have to make my decisions fast because it autoplays streams from the thumbnails.
> ill look for the about info page of the app tomorrow morning.

Also do all I have requested before, test the old app version and find one that works;

And just try to power off your device by removing from the wall, as anyone else has that issue, maybe yours device is just stuck.

Also for yours personal test you can use the apk from release to install on yours phone in case you have a android phone and see that the app just works.

Also you can disable preview from start in settings - Preview thumbnails players settings.

**Comment by dmitittt** [comment]
how do i downgrade on a smart tv? i dont have an android phone. 
the about page is in the beginning of the video.
ill try replugging my tv

**Comment by fgl27** [comment]
As I wrote uninstall download the apk from release https://github.com/fgl27/SmartTwitchTV/releases

I needed the about from inside the app the on in the side panel next to settings

**Comment by fgl27** [comment]
@dmitittt @hunter1749 

Is the problem resolved?

No one has shared anything I have requested please do infirm what is the reason
