### ISSUE TITLE
Stream keeps playing sound after closed

### ISSUE THREAD

**Issue by hunter1749** [fgl27/SmartTwitchTV#27]
Sometimes, after closing the stream, the sound keeps playing. It doesn't stop doing this even if I close the app. While this is happening, I can't open other streams and an error appears if I do so. I found that opening YouTube and a video in it (sometimes opening a video isn't required) fixes this issue.

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/26

add yours comments to the above issue please, also read all the discussion there and do all I ask is you wanna to resolve the issue, as I can't reproduce it.
