### ISSUE TITLE
Getting ads  now in mid stream for non sub sub channels seem fine. I  can refresh  and ad is gone but will  pop-up again.  

### ISSUE THREAD

**Issue by lilchina** [fgl27/SmartTwitchTV#28]
**Describe the bug*

Getting ads  now in mid stream for non sub. sub channels seem fine. I  can refresh  and ad is gone but will  pop-up again after a few seconds. Midroll ads I'm guessing. 

**To Reproduce**
4. See error something doesn't work

**Expected behavior**

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield, Xiaomi Mi box I II III IV, etc...
 - Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]

**Additional context**

**Comment by fgl27** [comment]
Give me some sample streams that have that. I have see none

**Comment by lilchina** [comment]
Shroud last night had it the most but didn’t notice it with smaller streamers 🤔

**Comment by lilchina** [comment]
I will test some bigger streamers  today  vs smaller  25k vs 1500 or smaller

**Comment by fgl27** [comment]
OK will test also, let me know what you can find.

**Comment by lilchina** [comment]
Ran all day today no ads so weird on any non sub streams close for now  if it gets  bad again  I will open and do more testing

**Comment by Kline-** [comment]
Looks like ads are back on the menu, at least for content being served from Chicago. I haven't seen any pre-rolls but I've had two mid-rolls so far. One I know was triggered by the streamer themselves (they announced they were going to run ads while taking a break). I don't know if the second mid-roll was done by the streamer or one of twitch's automatic ones though.

**Comment by fgl27** [comment]
Yes  seems region related I don't get any even when the steamer runs a ad.

Those that have ads let me know the type, frequency and region for the next few days.

**Comment by lilchina** [comment]
Yesterday  I got mid roll ads watching  Shroud . I'm  in Texas. Today not one ads.

**Comment by spamitinmy** [comment]
I'm getting mid roll ads from watching Lirik. Comes every 30 mins. I'm in Canada.

**Comment by fgl27** [comment]
I beleaved the ads stop if anyone has any let me know

**Comment by fgl27** [comment]
If the problem return let me know thanks... Close in this.
