### ISSUE TITLE
Firestick 4k  version 3.0.285 webview 75 sub emotes will not open

### ISSUE THREAD

**Issue by lilchina** [fgl27/SmartTwitchTV#29]
**Describe the bug**
To channels I sub to twitch emotes will not open, Bttv emotes do.
If I exit and close  the app, the twitch emotes will open. I  am not sure at what point it fails. I am testing  my other subs to see if I can replicate  the issue  and when it happens 

**To Reproduce**
4. See error something doesn't work

**Expected behavior**

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield, Xiaomi Mi box I II III IV, etc...
 - Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]

**Additional context**

**Comment by fgl27** [comment]
Emotes will not open... Do you mean the "write to chat" "twitch emotes" option's?

Or emotes in chat or self? Don't show?

**Comment by lilchina** [comment]
The pop-up window  to choose an emote  not the text window I just  verified  it was a issue on twitch side so everything is working now  close please. They  fixed it

**Comment by fgl27** [comment]
OK
