### ISSUE TITLE
Possible to do 4 simultaneous streams on 4k tv?

### ISSUE THREAD

**Issue by buddorz** [fgl27/SmartTwitchTV#3]
On devices like the Shield TV, would it be possible to have 4 simultaneous 1080p streams (say like the multiview on some satellite TV providers) going at the same time? I know it's not currently possible, but maybe the power is there?

**Comment by fgl27** [comment]
I guess it works didn't tried some day I will then I update here.
The key is not just the resolution it self, there is the bitrate and the compression level.

A higher bitrate needs more "CPU power", low end device as those xiaomi boxes for example can't play two 1080p60 on 7mbs bitrate or higher at the same time without lagging the device, it works but the control became laged and don't reply, so is needed to block the player from using higher bitrate at the same time for those devices with is technically simple to do..

The compression level is not a problem as most streams use low levels of compression I didn't manage to try two stream that use a higher compression level at the same time, but as this is hare is not something to worry too much, but also cost more processing time and lags a device more then lower compression levels.

Some day I will try this, the main problem is how much is need to change to add this, is not simple on the code side to make this properly work. Also not simple to use when you can only control with a d-pad.

I guess the simplest way is add a 4-way control you click it turns the single or dual stream on a 4 -way, and as you click on the live feed you populate the 4-way, when it's get full you click again and the player ask with to update (show 1 2 3 4 above it screen) and you choose the number to updates...

Also anyone can think on ways to describe how this could be on the controls side and share here, helps to have a proper idea of how it could be before starting wright the code.

**Comment by buddorz** [comment]
I'm not good at UI design, I just envisioned it behaving similar to how the PIP feature currently works, but a 2x2 grid that you can select the "screen" and then pick the stream in somewhat of a similar way.

**Comment by fgl27** [comment]
Yes is possible.

![SmartTV for Twitch_20200119_182529](https://user-images.githubusercontent.com/13755892/72688776-5ec54900-3ae9-11ea-9e55-fd38a575af89.png)

![SmartTV for Twitch_20200119_182519](https://user-images.githubusercontent.com/13755892/72688777-6258d000-3ae9-11ea-9a09-ef82a5b34466.png)

The shield didn't even hiccup, no skipped frames at all... but there is a small lag on the player controller UI, noticeable but not a problem as on the final version there will be optimizations not applied on this test apk...

I probably release this featuring in a week or so... :+1:

**Comment by buddorz** [comment]
Awesome! I appreciate the effort :) can't wait to give it a try!

**Comment by fgl27** [comment]
Debug apk for testing
https://drive.google.com/open?id=1drDwL-E6vk-PzShIMJkLkHAZu2dCV92x

The above is fully working but I will test for a few days if I change something I'll update the app the link will remain the same so I let you know and you redownload.

If you find a issue let me know what and how to replicate...

That is a debug app that install alongside the play one, so after install that you will have two, one stable the play one and the debug, it has a different icon color you will easi see with is with.

**Comment by fgl27** [comment]
I update the test apk from https://drive.google.com/open?id=1drDwL-E6vk-PzShIMJkLkHAZu2dCV92x

So anyone using re-download and install...

**Comment by fgl27** [comment]
App has be released on play.

**Comment by buddorz** [comment]
Just updated to the latest version, works like a charm!
Thanks for your hard work!
