### ISSUE TITLE
[Feature Request] Ability to "follow" channels without any Twitch account whatsoever. 

### ISSUE THREAD

**Issue by ACodingGenie** [fgl27/SmartTwitchTV#30]
**Please describe the feature.**
Is it possible to implement a feature that allows you to "follow" channels without ever linking any type of Twitch account whatsoever? By follow I don't mean actually follow the channel like we do on Twitch, I mean ability to add channels of your choice to "User's Live" or another category without linking a Twitch account to the app in any way (maybe by hitting the heart icon or something) so that we can only see channels we want. I removed my account for Twitch recently and this would be good tradeoff to still being able to see Twitch streams I want in the same place. So is this possible? Thanks.

**Comment by fgl27** [comment]
Just use a burner account with a burner email, gmail or wherever you wanna.

I have multiple twitch accounts for testing propurses.

I say that because even though it be possible to do that feature is not simple, I'll add this to the TODO list and maybe someday me or someone does it.

**Comment by fgl27** [comment]
I have add this to the app TODO so closing it

**Comment by fgl27** [comment]
related issue https://github.com/fgl27/SmartTwitchTV/issues/76
