### ISSUE TITLE
Unable to use 4 way multistream or PIP natively on Android TV (Sony X900H)

### ISSUE THREAD

**Issue by bossanovaorca** [fgl27/SmartTwitchTV#32]
**Describe the bug**

I've been using 4-way multistream on my two Nvidia Shields with no issue, but on my Sony X900H it always says my bit rate settings are too high to do multistreams even if I lower it to the absolute minimum values. Sometimes when trying to do PIP or when even just picking a single channel to watch, the stream preview will not render correctly. All devices are hard wired with Ethernet. Am I just unable to run this natively on my TV? Do I need to use a streaming box like the Nvidia Shield?

**To Reproduce**
1. Try to run PIP or 4 way multistream on Sony X900H Android TV
2. Observe that this error appears https://github.com/fgl27/SmartTwitchTV/blob/master/app/languages/en_US.js#L506-L507

**Expected behavior**
PIP or 4 way multistream should load all streams properly
 
 **Device:**
 - Sony X900H
 - Android TV v9

**Comment by fgl27** [comment]
>  Do I need to use a streaming box like the Nvidia Shield?
Any device that works OK, must support at least PP mode, yours seems defected.

**Did the app ever work OK on that TV?

Have you tried power the device off? by removing from the wall.**

This may happens if, the device is lagging that it can't play two video at the same time with is odd for a modern device, or the app can't allocate the codec with is also odd but may happen, both of those are random Android issues that get resolved after a power off/on.

If that doesn't solve

Share a screen shot or a picture of the **about** (side panel -> about) and **settings Blocked codecs** (btw you can drag and drop img to github post using a computer)

**Comment by bossanovaorca** [comment]
as far as I can remember the 4 way multistreaming didn't work correctly. PIP occasionally works but it's inconsistent. I did try powering the device off etc and the issue is still there for 4 way multistreaming

![20201220_142742](https://user-images.githubusercontent.com/13033321/102723983-b4920a80-42d1-11eb-8b98-cf893720b8ce.jpg)
![20201220_143126](https://user-images.githubusercontent.com/13033321/102723985-b5c33780-42d1-11eb-970a-dde2fda902a7.jpg)

**Comment by fgl27** [comment]
can you see right there on last image is the issue?

Max instance 2, yours device can only play two videos at the same time, using HW decoder, SW decoder is very very lag so even that be able to do more it won't do to the lack of performance.

**Comment by bossanovaorca** [comment]
oh ok I see now. looks like I should get another Shield for better streaming

**Comment by fgl27** [comment]
Is the best option for that device... maybe the device receives a update and it adds more instances, is very unlikely but maybe.

On android 9 and above a app can not release the codec instance as is possible to a app be playing on the background and that can cause the PP issue, even the issue of playback errors, as more then one app may be using the codec, also as there is only 2 the device may be too slow to release a codec instance and that causes the playback error.

This app will never not release a codec when it goes to background.

**Comment by fgl27** [comment]
I believed this is the error

![Screenshot from 2020-12-20 18-28-28](https://user-images.githubusercontent.com/13755892/102724832-3fcec880-42f1-11eb-91a0-1bbdd6ff61a7.png)

```
Caused by com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.AVC
       at **com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1356)**
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:820)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:917)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:475)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by bossanovaorca** [comment]
thank you for your help!
