### ISSUE TITLE
Chat window going black for 1 sec periodically

### ISSUE THREAD

**Issue by daxtep** [fgl27/SmartTwitchTV#33]
First, I want to thank you for this app, it's incredible how you are capable of using the ressources given better than a multi billion dollar company. Without this, I wouldn't be able to watch Twitch on my Mi TV stick.

To the problem: I'm on side-by-side view on 25% chat size. Every 45 secs or so, the chat window goes black for a sec and then the chat appears again. No messages lost, it just continues. 
I looked for some kind of refresh timer in the settings but couldn't find something related to that.

I have a MiTV-AESP0 with stock Android TV version 9, Kernel 4.9.113 with build PI.536.

Thank you in advance!

**Comment by daxtep** [comment]
Sorry, I have to correct my self. The issue only appears to happen in the first 3-5 mins after starting the stream. Afterwards it doesn't happen anymore.

This makes it a very low priority problem. 

I'm looking forward to support the app in the future! Have a great day.

**Comment by fgl27** [comment]
I can't replicate this on any device I have, this isn't a app problem is a "yours device issue".

If you can test the app on a different device so you can see it working properly please do, you can use this on any device as a phone download the app from https://github.com/fgl27/SmartTwitchTV/releases on none TV devices.

Check changes you did to the device settings (not the app settings) and apps that can control TV features as refresh rate or controls or anything related.

**Comment by fgl27** [comment]
Close do to inactivity.
