### ISSUE TITLE
Chat Errors and stream crashes

### ISSUE THREAD

**Issue by ACodingGenie** [fgl27/SmartTwitchTV#34]
**Describe the bug**
For some days I've been receiving these errors which sometimes loop (meaning my entire chat fills up with the erorrs) and crash the current stream you're watching and says "this streamer has ended" and returns to main screen. Sometimes the errors display a few times and the chat comes back and the stream keeps playing as well. Other times the stream buffers over and over. I don't know if this is a problem with Twitch servers or just my device. Thanks.

Chat: Connected as Anonymous
Chat: Websocket closed remotely...{"isTrusted":true}
OR
Chat: Error...{"isTrusted":true}
Chat: delay Base on Latency to Streamer

**Steps To Reproduce**
1. There really aren't any other than you're just watching a stream and this randomly happens without a warning.

**Expected behavior**
Chat shouldn't display the errors, the stream shouldn't crash and it should play like normal.

**Screenshots**
![ChatErrors](https://user-images.githubusercontent.com/68975831/104284518-21876300-5480-11eb-861a-d488e3783d18.jpg)
 
 **Device:**
 - TV Manufacture Device: Amazon Fire TV Stick Gen 2
 - Os version: Fire OS 5.2.7.7 | Home version: 6242056.1

**Comment by fgl27** [comment]
This is a connection issue, can be on Twitch side or on yours side.

**Comment by ACodingGenie** [comment]
Hmm...I think you're right, I can see the same chat problems here and there in Twire, although the stream doesn't buffer. I'll wait it out and hopefully it goes away in a few days. Thanks.
