### ISSUE TITLE
Android 4.4 support!

### ISSUE THREAD

**Issue by do2o** [fgl27/SmartTwitchTV#35]
Hi, amazing app!

Unfortunately I am unable to install it on my Smart tv as it supports Android 4.4. The app only support android 5.0+ version.

Is there any way to add legacy support for old tvs? Maybe a legacy apk

Any way to change the android build number?

Thankyou

**Comment by fgl27** [comment]
Android TV started on android 5, this app only work OK on android TV, meaning that you probably would have to use a mouse to use this app if someone manage to port it for a old OS.

I particularly will not do is a lot of work for something that may not even work, is a open source project that has detailed description on how to build and all the etc, if you wanna to try download android studio and have fun.

**Comment by do2o** [comment]
Ok no problem!
Thanks for the quick response.

I basically have to build the app and just change the build number to support 4.4 and leave the rest same as it is?

**Comment by fgl27** [comment]
If was just charge the min SDK I would do, you need to fix all the issues that the min SDK change will require that is the easy part as studio will let you know what isn't supported you can add support if possible or remobe... The day the apo build you need to run it and there may some. Issues there.

**Comment by fgl27** [comment]
Close do to inactivity... if you need help open a specific issue for your need.
