### ISSUE TITLE
Order the Followed Games screen

### ISSUE THREAD

**Issue by brendonrapp** [fgl27/SmartTwitchTV#36]
**Please describe the feature.**
The user's Followed Games screen currently orders games by the order in which the user followed them, which IMO is a very useless ordering.

A sensible ordering would be either Alphabetical or by Viewer Count, with being able to toggle between the two options being the ideal. Not sure if Viewer Count is available via the API call, but at the very least, client-side sorting into an Alphabetical format should be done. The page is just a mess the way it is now.

**Additional context or samples**
Not sure if this behavior is unique to the Android fork or if it's present in the Tizen app. I would suspect the latter but since I don't know, I submitted the feature request here.

**Comment by fgl27** [comment]
I don't plane to add this.

The server sends like this, some user follow 500+ games the app can only request 100 at a time to properly sort one must get all followed games before hand, with would make the app very slow to display the screen

If some day twitch add a proper api for games I update the support current API the app uses is not even supported by twitch, what that means they don't provide proper followed game api
