### ISSUE TITLE
F-Droid Repository

### ISSUE THREAD

**Issue by NightHammer1000** [fgl27/SmartTwitchTV#37]
A F-Droid Repository would be nice.

To make Updating on Playstore-less Devices like FireTV and Chinaboxes less of an Pain in the ass.

https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by fgl27** [comment]
Not needed the app will receive auto update feature this week

**Comment by fgl27** [comment]
The app now can update it self for user that don't use play store, you need to be on version 3.0.299 or up for this to work so only on next update after the one released today that will work.

enjoy.
