### ISSUE TITLE
Player info disappears after hovering player options in stream

### ISSUE THREAD

**Issue by spamitinmy** [fgl27/SmartTwitchTV#38]
**Describe the bug**

In a stream, when the "Player status visibility" option is set to "When player info is visible", it is only visible when initially showing player info. Once you select to a button, like any of the options in the player info, the player status disappears. 

**To Reproduce**
1. Go to a live stream
2. Click on 'Enter' button to reveal the player info
3. Click down to the options available in the stream

**Expected behavior**
Stream info should be shown at the top right of the video.

**Screenshots**
First screenshot, after pressing 'Enter', it shows player info:
![IMG_7529](https://user-images.githubusercontent.com/17346857/106634629-f5767380-654d-11eb-9961-ec1f136d50dd.jpg)

Second screenshot, after pressing down to go to the available options at the bottom of the player, player info disappears:
![IMG_7530](https://user-images.githubusercontent.com/17346857/106634644-f7d8cd80-654d-11eb-95c7-dfd483d9362f.jpg)

 **Device:**
 - TV Manufacture Device: Nvidia Shield 2019, Vizio PX65Q TV

**Additional context**
I remember vaguely this behavior isn't like this in previous versions.

**Comment by fgl27** [comment]
Expected behaviors, you selected the controls the app will show you only that as is clear that this is hours focus now, the same for the progress seek bar....

You wanna see it all just press enter once.

What is the issue on this behavior?

For me looks and works much better. Also has be like this for a long time.

**Comment by fgl27** [comment]
Close to do lack of communication
