### ISSUE TITLE
Navigation buttons control wrong menu in multistream

### ISSUE THREAD

**Issue by bossanovaorca** [fgl27/SmartTwitchTV#39]
**Describe the bug**
When trying to replace an existing stream in multistream mode, the navigation buttons will continue to control the bottom stream selector ribbon menu rather than the popup dialog containing the 4 existing streams to replace

**To Reproduce**
1. Open four streams in multistream mode
2. Bring up the stream selector ribbon menu (press "up")
3. Select a stream, the stream replacement dialog should appear
4. Use directional buttons to pick a currently open stream to replace
5. Observe that the directional buttons appear to continue affecting the bottom ribbon menu rather than the popup dialog

**Expected behavior**
After opening the popup dialog to replace a currently open stream, the navigation buttons should control the dialog UI rather than the bottom ribbon menu

 **Device:**
Tested on multiple devices, Nvidia Shield, Nvidia Shield Pro, Sony X900H, LG OLED65E8PUA

**Additional context**
This seems to be a recent regression

**Comment by fgl27** [comment]
Thank you fix it here https://github.com/fgl27/SmartTwitchTV/commit/77dc405499aa349d44dd088dce895dd58f59db19

Use the update dialog to update.

**Comment by bossanovaorca** [comment]
Thanks for the quick fix!
