### ISSUE TITLE
Changing  default player quality to 720p doesn't  change bitrate  

### ISSUE THREAD

**Issue by lilchina** [fgl27/SmartTwitchTV#40]
**Describe the bug**
When I  change the default player quality  to  720p  certain  1080p stream  do not  change  to 720p biterate  stream. I'm getting data from cell phone  so I  am limited  to 5 mbps which is enough for 720p. If I choose  480p the  1080p stream bitrate  changes to 480p bitrate.
![2F757A08-859E-4E7C-92FD-8DC406557260](https://user-images.githubusercontent.com/58664301/108528550-26b6a980-7299-11eb-82ba-52c350e10389.jpeg)
![D7AF3C32-0491-49EF-91AE-7F3589275F8F](https://user-images.githubusercontent.com/58664301/108528602-33d39880-7299-11eb-9332-cba632b84817.jpeg)

**To Reproduce**
4. See error something doesn't work

**Expected behavior**

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield, Xiaomi Mi box I II III IV, etc...
 - Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]

**Additional context**

**Comment by lilchina** [comment]
![89FCE1C7-0ADF-4CF4-81ED-7803AE3CE299](https://user-images.githubusercontent.com/58664301/108528772-62ea0a00-7299-11eb-8201-cbe60142c6b4.jpeg)

**Comment by lilchina** [comment]
![image](https://user-images.githubusercontent.com/58664301/108529166-d12ecc80-7299-11eb-92e5-1ea7fc4fb20a.jpg)

**Comment by lilchina** [comment]
![image](https://user-images.githubusercontent.com/58664301/108529557-3387cd00-729a-11eb-87b2-f25e0ab83277.jpg)
Switching to 480p bitrate changes just not for 720p

**Comment by lilchina** [comment]
The curvyelephant  stream is 1080p and it it recognized  my setting of 720p  and  changes bitrate. Mekabear and many other just constantly  buffer and doesn't switch to 720p  her source is  936p60 FYI

**Comment by lilchina** [comment]
Hmm maybe source = 1080p check  default  player  quality if 720p  then bitrate= 720p  bitrate . But if source is undefined  for example  936p60 then default  player quality  can't change  because  variable  not recognize?  So it doesn't change steam to  720p  bitrate.  Am I  thinking this is what's happening?

**Comment by lilchina** [comment]
Well that's not it I just checked my other streams that are 1080p60 and they aren't switching to 720p 30. They are streaming as source.   Strange some  sources  at 1080p60  switches to 720p 30 and others don't.  hmmm confused.

**Comment by fgl27** [comment]
Mekabear stream doesn't have 720p30, so it default to source

**Comment by fgl27** [comment]
I can improve this so it stay at 720 at least

**Comment by fgl27** [comment]
What I recommend is to let it at auto, and limit the resolution/bitrate it self

That is the most effect way to prevent, it from going above a resolution and or bitrate

**Comment by fgl27** [comment]
Like this

![Screenshot from 2021-02-19 13-45-49](https://user-images.githubusercontent.com/13755892/108534353-d18a9000-72b8-11eb-8209-eb273c391910.png)


will prevent high bitrates, but will allow any resolution, is the best option

**Comment by lilchina** [comment]
Ok when I click on  my select  button on my remote to pull up  setting  choose  the select quality icon 720p30 isn't a choice only  720p60 which  give me buffering, 
![image](https://user-images.githubusercontent.com/58664301/108534479-cd9e4400-729f-11eb-831a-e2311d342e85.jpg)

**Comment by fgl27** [comment]
> Ok when I click on my select button on my remote to pull up setting choose the select quality icon 720p30 isn't a choice only 720p60 which give me buffering,
> ![image](https://user-images.githubusercontent.com/58664301/108534479-cd9e4400-729f-11eb-831a-e2311d342e85.jpg)

can you refresh the issue page on a browser???

I already inform you what to do

**Comment by lilchina** [comment]
Oh the streamer  has to make  it a choice when they start their stream. I thougt the player  down converted it within. Ok thanks got it. Spectrum  no internet  for  5 days  otherwise  wouldn't  even notice  this  lol close

**Comment by fgl27** [comment]
OK I'll improve the default quality selection then I close.

Use auto + bitrate limit and you will be fine
