### ISSUE TITLE
Highlight @streamer messages (Dark red background, the @ is blue) regression

### ISSUE THREAD

**Issue by bossanovaorca** [fgl27/SmartTwitchTV#41]
**Describe the bug**
I have the "`Highlight @streamer messages (Dark red background, the @ is blue)`" chat option enabled but it seems that sometime in the last week or so it has not been functioning properly anymore

**To Reproduce**
1. Enable "`Highlight @streamer messages (Dark red background, the @ is blue)`" chat option
2. Observe a chat room and see if `@streamer` messages are not highlighted

this seems like a regression unless a setting has been added or moved. I've had it enabled for months but it stopped working very recently

**Comment by fgl27** [comment]
This isn't a app issue is something else, there was no change in the chat implementation for a wile...

I didn't notice before as my TV device is fine then I use my phone and it happen... Then it stopped harkening all became fine.

This is a odd one...

Can you share a screen shot or picture of the in app about... Is on the side under settings.

Thanks

**Comment by bossanovaorca** [comment]
sure here is one screenshot. it's the same for all of my NVIDIA Shields

![Screenshot_20210402-104155](https://user-images.githubusercontent.com/13033321/113433405-c2612c80-93a4-11eb-84da-f3e66f5dc74e.png)

**Comment by fgl27** [comment]
OK this is odd on the shield I have access no issue, not that I have notice.

I will take a look to see what is causing it.

**Comment by fgl27** [comment]
The above just fix it, use the update dialog to update and will all working, Thanks!

**Comment by bossanovaorca** [comment]
I just got the update and it's working again. thanks for the quick fix!
