### ISSUE TITLE
Display bug 

### ISSUE THREAD

**Issue by kurtdh** [fgl27/SmartTwitchTV#47]
Watch a stream. Press up to view list of streams. Select a stream that just went offline. It states the stream is offline. 

Then press select on the remote to show the stream name and statistics. You will notice the Twitch channel in the top left corner of your screen is showing the offline Twitch channel instead of the current channel.

**Comment by fgl27** [comment]
Thank you the above change fixes it.

If the app is open click on the update dialog to receive the fix, if the app is closed will be OK on next start.
