### ISSUE TITLE
Livestream still plays after exiting

### ISSUE THREAD

**Issue by hunter1749** [fgl27/SmartTwitchTV#48]
Sometimes, after I exit a livestream, audio still plays in the background until I shutdown the app or play a video on YouTube. You might remember my issue from a few months ago, and it's still here, but I don't think I got "Error Code 100" at that time, so I hope this helps more now, otherwise tell me what else I should provide you with.

I also have a question about filtering emotes - Is there an option that would disable some BTTV/FFZ emotes in live chat?

**Comment by fgl27** [comment]
Error codes start at 1000, and 1000 is "Caused by an error whose cause could not be identified"

O can't replicate this, can you share a bug report?
here a how to https://github.com/fgl27/SmartTwitchTV/issues/14#issuecomment-673887650

You can't filter chat with this app.

**Comment by hunter1749** [comment]
I still haven't been able to reproduce the issue either, so I'll email you the bug report when I get it happens again.

**Comment by hunter1749** [comment]
Update: Have tried to send myself bug reports now, but none of them come to my Gmail inbox, what am I missing here?

**Comment by fgl27** [comment]
If you click in send as show on the image bellow, I don't know.

![BugReportSender_20200814_020831](https://user-images.githubusercontent.com/13755892/90215794-37123700-ddd3-11ea-85c9-01b0ad27ac62.png)

check  span box or something like that on the email you use.

**Comment by hunter1749** [comment]
I'll experiment with different emails and different report sizes, if it sends, I will forward it to you as soon as possible.

**Comment by hunter1749** [comment]
Sorry, I just can't send myself the bug report from the TV. Maybe it it works some day I can send it to you, but for now, I will stop trying.
