### ISSUE TITLE
Watched parts of the stream sync

### ISSUE THREAD

**Issue by LordBoos** [fgl27/SmartTwitchTV#5]
**Please describe the feature.**
Official twitch apps tracks which parts of stream I've watched and I can then see on the stream recording where exactly I stopped watching and I can easily resume where I left. 
SmartTwitchTV does not do this. Whole video appears as unwatched even when I watched eg. 50% of the stream, making it hard to find the exact moment I left.

**Comment by fgl27** [comment]
The API that provides that sync is not open to third party app.

I made a in app history but it doesn't sync with twitch and can't sync from.

What happens on the app stays on the app...

The in app history is to be release in this week...

**Comment by LordBoos** [comment]
Thanks for the reply. In-app history is good enough as I almost exclusively watch twitch on my TV. So I'm closing this issue.

**Comment by fgl27** [comment]
The update for the user history was released (app V 2.0.107)... you need to update from play to fully receive the new featuring...

If you find something that can be improved on that or else where let me know on a new issue.
