### ISSUE TITLE
Feedback from the recent side panel changes

### ISSUE THREAD

**Issue by hunter1749** [fgl27/SmartTwitchTV#54]
After the newest update, where the side panel's graphics were also changed a little, I've noticed that the visibility of the selected tab is worse than it was before (for me especially, since the screen is darker), but also that when you change the selected tab, the highlighted part behind the icon doesn't move with the highlighted part of the text (I checked the older version and I see that it was intented like that, though to me it would make more sense to move them together with how the current design looks because of the gradient background style). Including an image of how that looks and an image of how the side bar could be improved (showing the one from YouTube).
https://i.imgur.com/4JbNVcz.png
https://i.imgur.com/eBxqG0T.png

**Comment by fgl27** [comment]
I like the way it's. It doesn't move so you know were you are if you press ever it moves

**Comment by fgl27** [comment]
As I write before if anyone wanna to add themes to the app they can, as long is something that can be changed via setting.

**Comment by hunter1749** [comment]
I don't see where side panel can be changed, also I think you mentioned
somewhere the font or font size can be changed somewhere, but I can't find
it.

V V ned., 18. jul. 2021 ob 07:09 je oseba Felipe Leon <
***@***.***> napisala:

**Comment by fgl27** [comment]
I wrote... if anyone wanna to add, meaning there isn't any theme or logic implementation for anything related to the side panel theme.
But anyone can add anything to this app, as this is a open source project. I will not add themes to the side panel myself but anyone can.

**Global app font size offset**

![Screenshot from 2021-07-19 00-10-03](https://user-images.githubusercontent.com/13755892/126097214-fb32aa35-0a64-453e-aeca-58b3fdd28335.png)

**Comment by hunter1749** [comment]
Ok, thanks for the clarification.

V V pon., 19. jul. 2021 ob 05:14 je oseba Felipe Leon <
***@***.***> napisala:
