### ISSUE TITLE
Block bots and bot commands from chat

### ISSUE THREAD

**Issue by ja-som** [fgl27/SmartTwitchTV#55]
Hi,
is it possible to add option to completely block bots (Nightbot, etc.) and also commands for bots ("!uptime" etc.) from chat?

**Comment by fgl27** [comment]
Sure I can add this, using the bellow for checking

> Nightbot.
> StreamElements.
> Moobot.
> Deepbot.
> Wizebot.
> Ankhbot.
>Streamlabs.
> Phantombot.
> Xanbot.

Plus bbtv api used for emotes, has a parameter `bots` for knows chat bots of that channel, they don't list all bots for all channels but it can be use to improve the list.

When this is available I let you know.

**Comment by fgl27** [comment]
I have found this commands:

- !uptime.
- !watchtime.
- !commands.
- !nightbot.
- !followers.
- !bttv.
- !game.
- !schedule.

If there is more commands or bots that you know let me know.

**Comment by ja-som** [comment]
Well there is tons of commands, every channel can have it's own custom commands, it will be hard to name them all. Kinda same with bots, some channels changed its name to streamer name.
Not sure if it will work, but for commands block message when it starts with ! and it has only one word right after that.

**Comment by fgl27** [comment]
The feature was added, if the app is open click on update and changelog to update.

![Screenshot from 2021-07-21 20-04-30](https://user-images.githubusercontent.com/13755892/126573402-e231de31-4164-4b21-85fd-ab464ab1ff7a.png)
