### ISSUE TITLE
option increase timer before ending an offline stream

### ISSUE THREAD

**Issue by henriklb** [fgl27/SmartTwitchTV#59]
option increase timer before ending an offline stream  

I tend to want to select the option ‘wait for stream to come back online’ but the 3 second time out is very short and I barely have enough time to find my remote let alone press any button

**Comment by fgl27** [comment]
![Screenshot_20210723-204342_SmartTV_Client_for_Twitch](https://user-images.githubusercontent.com/13755892/126850751-de425f7e-3736-447c-8ef9-df964e951434.png)

**Comment by henriklb** [comment]
thanks!  I was not aware if this  option. May I suggest to increase the default timeout from 3 to 6-9 seconds
