### ISSUE TITLE
VOD playback speed

### ISSUE THREAD

**Issue by gabrieluly** [fgl27/SmartTwitchTV#6]
Would it be possible to add a feature to control vod playback speed? I watch a lot of vods and would really like to watch some faster, like 1.5x or even 2x. It could be placed with the other controls since some of those buttons are only suitable in live mode (like chat delay, for example).

**Comment by fgl27** [comment]
you can't see the speed control?
https://youtu.be/ovHBcDUhH84?t=98

works for live, vod and clips

**Comment by gabrieluly** [comment]
oh ok, I have the Samsung Tizen version, thanks for clarifying
