### ISSUE TITLE
Feature request - Set default latency to broadcaster

### ISSUE THREAD

**Issue by AndMel87** [fgl27/SmartTwitchTV#61]
Like the mobile app, STVCfT runs about 10-15 seconds behind the web viewer. I love being able to scrub ahead, but when switching a lot of streams it would be a lot easier to have a global setting that sets the latency for you. I also don’t know if it’s even possible to scrub ahead for the small player in 50/50 multi-stream, which leads to a major delay between streamers.

**Comment by fgl27** [comment]
There is that option for low latency on the app

![Screenshot from 2021-07-31 08-34-08](https://user-images.githubusercontent.com/13755892/127738631-f6bc6142-0eb2-493a-b04f-d593492c83b5.png)

You must press enter to enable it, when you it will enable to all streams, and you can check the value of the latency on the player status on the top right corner as show on the image below "Latency To Broadcaster"

![Screenshot from 2021-07-31 08-34-14](https://user-images.githubusercontent.com/13755892/127738649-7200c762-240d-459b-a81c-47a3aeb56e98.png)

**Comment by fgl27** [comment]
Regarding the use of the progress bar the bar above the pause button from last image...

You can use it to manually sync two streams, but it only controls the main player.

The main player is the big player when using the Picture in Picture mode, the top player from 50/50 mode or the top left or big one player of the multistream mode.

**Comment by AndMel87** [comment]
Oh excellent, thank you!
