### ISSUE TITLE
Feature Request - Ability to switch main & small player during 50/50 multi stream

### ISSUE THREAD

**Issue by AndMel87** [fgl27/SmartTwitchTV#64]
From what I can gather right now, the only way to do this would be to go to big/small multi-stream (button 2?) and then back to 50/50-mode. Could perhaps be handled with long-pressing the D-pad down, so that pressing switches audio while holding switches video source, so that one more easily can define which is the main stream.

**Comment by fgl27** [comment]
I can allow the same process that is used for the picture in picture mode here, with is hold down audio all, click down switch players.

**Comment by AndMel87** [comment]
Excellent. My suggestion would be click for audio and hold for video though, as A) at least for my case I switch audio source most often, and B) switching audio source seems less resource heavy in case one were to accidentally click the button.

**Comment by fgl27** [comment]
This feature was added update the app so you can use it.
