### ISSUE TITLE
Feature Request - Some way to keep main stream active while browsing the app

### ISSUE THREAD

**Issue by AndMel87** [fgl27/SmartTwitchTV#65]
Would be great for longer streams or while looking up another streamer for multi-stream without having to shut off the main stream.  I envision something like a floating preview-window in the top-right corner when backing out from the main player.

**Comment by fgl27** [comment]
I don't plan to add this, as the app has a in player preview system

I will add a search option to the preview someday ad some other improves

the preview is the bellow that show when you press up when watching something

![Screenshot from 2021-08-01 07-42-37](https://user-images.githubusercontent.com/13755892/127767987-324fe0c8-62e8-4cf6-9052-eb016e585fd9.png)
