### ISSUE TITLE
Feature Request - Shortcut to the Controls-screen

### ISSUE THREAD

**Issue by AndMel87** [fgl27/SmartTwitchTV#66]
There are a lot of shortcuts to keep track of. Could one dedicated button bring up the Controls-screen as an overlay only while pressed? That way it would give a quick reference without having to back out to the main menu.

**Comment by fgl27** [comment]
I will add a option to a key for example a numeric and letter key.

**Comment by fgl27** [comment]
I have added a option using the key 5 or letter "C", plus a button controls option see bellow, will be available on next app version;

![Screenshot from 2021-08-10 03-35-31](https://user-images.githubusercontent.com/13755892/128819633-c1100394-e711-4ce7-bf6a-97fd4bc8ccec.png)

![Screenshot from 2021-08-10 03-35-35](https://user-images.githubusercontent.com/13755892/128819647-b3873e04-1d7f-43ad-8ed8-329406a98ee5.png)

**Comment by AndMel87** [comment]
Excellent work, thank you!

**Comment by fgl27** [comment]
feature released, if the app is open use the update option to update, if not open next time you do will be there.

thanks fro the help.
