### ISSUE TITLE
Feature Request - Highlight messages FROM @streamer only

### ISSUE THREAD

**Issue by AndMel87** [fgl27/SmartTwitchTV#68]
The chat option Highlight @streamer needs an additional «only messages FROM streamer» choice in the settings.

With some of the bigger streamers, a lot of people @ the streamer looking to get their attention, so the chat window highlights a disproportionate number of messages. It’d be great to not have to highlight those, while still highlighting messages from the streamer themselves.

**Comment by fgl27** [comment]
Yes this can be done, I probably do this on the same day I do the other highlight you requested.

On the next day I have some free time and wanna to work on this.

**Comment by fgl27** [comment]
feature released, if the app is open use the update option to update, if not open next time you do will be there.

thanks fro the help.
