### ISSUE TITLE
App crashing upon adding new user

### ISSUE THREAD

**Issue by kerokero99** [fgl27/SmartTwitchTV#7]
Recently installed this app on my Fire TV Stick 4K (mantis). It does work, but I am not able add a user. After entering my username, the app semi-freezes. I am still able to navigate the side menu (options, about, etc) but I can't browse the directory or load a stream. Only way to get the app working again is to force close it, but my user remains unadded. Went through common troubleshooting processes like restarting my device, trying different builds, nothing works.
I'd appreciate if someone could look into it.

**Comment by fgl27** [comment]
What is the username?

Do you have the bellow app installed on the device?
https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by kerokero99** [comment]
Username is rerorero__

Installing said app unfortunately couldn't solve the issue.

**Comment by fgl27** [comment]
User works just fine for me, but I don't have a "Fire TV Stick " and doesn't makes sense not be able to add a user.

If you clean the app data and don't try to add a user can you play streams?

Can you connect to adb on that device?

**Comment by kerokero99** [comment]
I can use the app just fine but as soon as I enter my username the problem occurs. Yes I can use adb on that device

**Comment by fgl27** [comment]
OK that helps, here is the a debug apk, unzip, install and open it

[app-debug.zip](https://github.com/fgl27/SmartTwitchTV/files/4250213/app-debug.zip)

Connect via adb,  on the computer open chrome and open this link

chrome://inspect/#devices

click inspec **WebView in com.fgl27.twitch.debug**

If the console window is showing OK (as bellow image), add yours user

Show the me result

my is

![Screenshot from 2020-02-25 10-32-59](https://user-images.githubusercontent.com/13755892/75252117-c6427880-57ba-11ea-9653-5fce28d234ff.png)

**Comment by fgl27** [comment]
So?

**Comment by fgl27** [comment]
closed do to inactivity.
