### ISSUE TITLE
Feature Request - Sort Twitch channel emotes to the top of the Twitch emotes category

### ISSUE THREAD

**Issue by AndMel87** [fgl27/SmartTwitchTV#72]
That way when I open Twitch emotes category, my streamers’ emotes are on top, instead of way down the list. Other subbed channels emotes should follow, then the global Twitch emotes, mimicking how the mobile app functions.

**Comment by fgl27** [comment]
I don't know if is possible, the API that allows to get user emotes don't provides any reference for with streamer the emote belong to.

You can see here how the emote list comes from the server

https://github.com/fgl27/SmartTwitchTV/blob/master/jsonreferences/twitch_emotes.json

Also Twitch will no longer support that API after february of next year, they don't provide a replacement, the app will only be able to show global Twitch emotes.

**Comment by AndMel87** [comment]
Oh, I thought it would have been possible based on most emotes seem to have a channel-specific prefix, but no worries then.

With them no longer supporting the API, does that mean no longer channel specific emotes at all? What about BTTV/FFZ/7TV?

**Comment by fgl27** [comment]
Is a twitch thing only applyes to twitch api see it here https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/

**Comment by fgl27** [comment]
I will add this to my TODO list and re check in the future if possible
