### ISSUE TITLE
Feature Request - 50/50 multi-stream in vertical split

### ISSUE THREAD

**Issue by AndMel87** [fgl27/SmartTwitchTV#73]
I would love to be able to set streams side by side horizontally to maximize the size of the stream window. In order to keep chat window, the overlay-option from main stream could be utilized (see attachment)

![chat_overlay](https://user-images.githubusercontent.com/47888106/127732125-15e28a46-6bc7-4803-8c8e-276174b703e1.png)

**Comment by fgl27** [comment]
I don't get it... Can you show me a example as the bellow?

![example](https://user-images.githubusercontent.com/13755892/127738436-1943f3b5-062f-42cf-bdac-444009f11a8d.png)

Just drag a image to a comment will show.

**Comment by AndMel87** [comment]
![vertical_split](https://user-images.githubusercontent.com/47888106/127739102-51167c51-50ae-4064-9ab7-8ca90625c2f8.png)

I'm thinking something like this to maximize the size of the actual stream, while utilizing blank spaces. Of course depends on aspect rations, which I'm not able to account for at the moment.

**Comment by fgl27** [comment]
You can't do that with player that have a aspect ratio of 16 by 9 without stretching/zoomed the image, I don't think anyone wanna to see a stretching or zoomed in video.

See the below images the size of the player on 50/50 mode is equal to the size of the multistream mode, that is already horizontally in a side by side way.

# 50/50 mode

![Screenshot from 2021-08-01 05-39-11](https://user-images.githubusercontent.com/13755892/127766620-66a837ed-3f85-41a1-8923-6c57eea3c623.png)

# multistream mode

![Screenshot from 2021-08-01 05-38-36](https://user-images.githubusercontent.com/13755892/127766627-3825ebf7-a02e-42f5-bf84-f75c6b8d887f.png)

**Comment by AndMel87** [comment]
Ah, you are absolutely right! Then I absolutely agree that the current setup for 50/50 is the best option.
