### ISSUE TITLE
Instance message appears in the middle of the screen when opening a livestream

### ISSUE THREAD

**Issue by hunter1749** [fgl27/SmartTwitchTV#74]
**Describe the bug**
Discussed before [here](https://github.com/fgl27/SmartTwitchTV/issues/63#issuecomment-894151427).
As you will see in the video, it doesn't happen always (once out of six tries), and also sometimes it lasts a little longer than it did in the video.

**To Reproduce**
Click on any livestream, then the message might appear, like at 00:15 in the video below.

**Expected behavior**
No message on the screen.

**Video (big compression)**
https://user-images.githubusercontent.com/44819251/128566433-4bf53d3c-996d-49d0-ba4a-1c0f1fff0560.mp4
 
 **Device:**
Some TCL television.

**Comment by fgl27** [comment]
OK, thank you. that is fixed on next app version.

can you share a image of the bellow settings option, so I can improve somehtings

![Screenshot from 2021-07-31 09-02-17](https://user-images.githubusercontent.com/13755892/127739308-d33366c5-4ef4-4787-8454-0239c6b4fe1c.png)

**Comment by hunter1749** [comment]
Yes, I think it's fixed now.
Screenshot (also if you maybe know where to look for a screenshot that I take directly on tv, or how you do it for yours, because I can't find it, so this image below is lower quality):
![image](https://user-images.githubusercontent.com/44819251/128603426-bd6eedf8-579a-4c30-b81a-87a6253687dc.png)
The one above is enabled and the one below is disabled.

**Comment by fgl27** [comment]
OK I can see and understand. Is very odd that the device doesn't support more then one instances...

On Android TV there is no standard for screenshot as on phones, you need to search about yours device.
