### ISSUE TITLE
Possible code regression with stream lagging

### ISSUE THREAD

**Issue by kurtdh** [fgl27/SmartTwitchTV#77]
Related to the previous bug where the stream would lag when you opened/closed the chat window. 

Since the latest update, the bug now exists when source in settings is set to "auto", whereas before, it would only occur when it was set to "source." Latest released just moved the bug from one setting to another..

**Comment by fgl27** [comment]
I push two app update, one fixed the source the outer something else, but sometimes takes a long time for the update show up on the store, I only push a app update notification when the store confirms the release.

**Comment by kurtdh** [comment]
Quick question:
  

  
I downloaded and am using your app on my Windows 11 machine. I noticed the picture in the app is a lot more washed out looking than the video pulled up on the Twitch website. Is there a way to adjust the contrast and brightness levels in the app somehow?
  

  
Kurt   
  
  
  
  
  
  
  

  
  
>

**Comment by fgl27** [comment]
seems you don't have like yours device screen, the app can't control picture quality, find a solution specific for yours device.
