### ISSUE TITLE
Home screen channels stopped refreshing

### ISSUE THREAD

**Issue by G0mez82** [fgl27/SmartTwitchTV#78]
**Describe the bug**
On my shield tv, home screen channels for smart tv client for twitch won't update/refresh anymore. Now it shows empty list all the time even there is streamers online. Reinstalled app but it didn't help. This started right after I updated to 4.0.1_V8

**Device:**
 - Shield TV 2015 
 - Shield Android TV SW Version 8.2.3

**Comment by fgl27** [comment]
I have transferred the issue to the proper repo.

**Comment by fgl27** [comment]
The problem is resolved, a new version was released will be available on player store in a few hours.

Thanks
