### ISSUE TITLE
Blacklist user or message

### ISSUE THREAD

**Issue by hunter1749** [fgl27/SmartTwitchTV#83]
**Please describe the feature:**
Filtering unwanted messages, so if I send a message in chat "test PogChamp" I could add a filter phrase "test" or "PogChamp" somewhere in the settings so I don't see messages that contain those phrases.

**Additional context or samples:**
BTTV browser extension has that option, so I was thinking it could be made similar to that if it's not too difficult. It also has the option to block filter out usernames in chat (images below).
![image](https://user-images.githubusercontent.com/44819251/131229323-6b95bd11-c1ad-4cd1-87ba-7e99936509aa.png)

**Comment by fgl27** [comment]
I understand it, is technically simple to filter chat, but need a UI to be able to do so.

This is the same case as https://github.com/fgl27/SmartTwitchTV/issues/69

I have added the request on the app TODO list next to that issue request.

https://github.com/fgl27/SmartTwitchTV/blob/master/apk/TODO.md
