### ISSUE TITLE
Screen is cut off on not 16:9 aspect ratio tablet device

### ISSUE THREAD

**Issue by xvasonix** [fgl27/SmartTwitchTV#85]
**Device:**
8.0" 1280 x 800 - LG G Pad 8.0
11.0" 2000x1200 - Lenovo P11
12.4" 2800 x 1752 - Samsung Galaxy S7+

VideoPlayer is good. but D-pad, Chat and Every UI is cut off.
Horizontal scroll is enabled. but can't scrolling. plz fix it...

**Comment by fgl27** [comment]
Let me see

**Comment by xvasonix** [comment]
This is 12.4" 2800 x 1752 - Samsung Galaxy S7+ device.
Right side is cut off.. other tablet device is same!
but Galaxy S21 Ultra (20:9 ratio 3200 x 1440 resolution)  everything is fine!

![Screenshot_20211123-090059_SmartTV Client for Twitch](https://user-images.githubusercontent.com/94818711/142953205-9deb305e-2554-4e01-b1c1-1d0f3ea1b3a6.jpg)
![Screenshot_20211123-090134_SmartTV Client for Twitch](https://user-images.githubusercontent.com/94818711/142953211-a405ffde-3185-4360-ace5-d57f306a85d6.jpg)
.

**Comment by fgl27** [comment]
OK thanks...

Some devices report two different values for the screen size with complicates things, as one is correct one isn't.

I will have to redesign some elements size base on the correct value.

I let you know when I manage to fix it all.

**Comment by fgl27** [comment]
I push a minor change to improve aspect ration and related, but on the devices I have the issue was on the horizontal axis and on yours devices is on the vertical so I don't know if any improve was done.

But any way let me know. :+1:

**Comment by xvasonix** [comment]
Oh, I'm sorry I forgot about this issue.

I still have a problem.

Here's my sample code. It's not enough, but please review it.


`// BodyfontSize is used for px to em calculation used by scroll functions
var BodyfontSize;
var scaleFactor;
var currentWidth;
var currentHeight;
var scaledWidth;
var scaledHeight;
		
function calculateFontSize() {
    var offset = 0;
    //Prevent crash in case Settings_value is not yet loaded
    try {
        offset = Settings_value.global_font_offset.values[Main_getItemInt('global_font_offset', Settings_value.global_font_offset.defaultValue) - 1];
    } catch (e) {
        offset = 0;
    }

    // Initial sizes.
    var initialFontSize = 29 + offset,
        initialWidth = 1920,
        initialHeight = 1080;
	
		

    // Get current client/screen height.
    currentHeight = window.innerHeight;
	currentWidth = window.innerWidth;
	
	// Get direction
	initialRatio = initialWidth / initialHeight;
	currentRatio = currentWidth / currentHeight;
	
	if(currentRatio >= initialRatio){
	// Horizontal Wide mode
		
	// Calculate scale factor and scaled font size.
    scaleFactor = currentHeight / initialHeight;
    BodyfontSize = initialFontSize * scaleFactor;
	// Calculate scaled body/divs size.
    scaledWidth = initialWidth * scaleFactor;
	//Set new body width/height recalculated to 16 by 9 and scaled fontSize 
    document.body.style.width = scaledWidth + 'px';
    document.body.style.height = currentHeight + 'px';
    document.body.style.fontSize = BodyfontSize + 'px';
	} else {
	// Vertical Wide mode
		
	// Calculate scale factor and scaled font size.
	scaleFactor = currentWidth / initialWidth;
    BodyfontSize = initialFontSize * scaleFactor;
	// Calculate scaled body/divs size.
	scaledHeight = initialHeight * scaleFactor;
	document.body.style.width = currentWidth + 'px';
    document.body.style.height = scaledHeight	+ 'px';
    document.body.style.fontSize = BodyfontSize + 'px';
	
	}
	
	// Fit to full Screen ??
	//document.body.style.width = currentWidth + 'px';
    //document.body.style.height = currentHeight	+ 'px';
    //document.body.style.fontSize = BodyfontSize + 'px';
	
	
    BrowserTestSetVideoSize();

    //Some sizes are based on VH but some devices have a wrong value for CSS vh
    var ele = Main_getElementById('settings_scroll');
    if (ele) {
        ele.style.fontSize = (currentHeight * 0.0267) + 'px';
    }

    var cssClass = '.side_panel_fix{font-size: ' + (currentHeight * 0.0265) + 'px;}';

    Main_innerHTML(
        'vh_class',
        cssClass
    );
}`

**Comment by fgl27** [comment]
Review what yours post makes no sense

**Comment by xvasonix** [comment]
> 
Sorry for my bad English. This is part of "SmartTwitchTV/tree/master/app/general/resize.js" file of 30 line.

Detect screen direction is vertical or horizontal ,, and set document.body size to right direction or fit fullscreen.

**Comment by fgl27** [comment]
That is ok.

I get it, if the ratio is smaller the 16/9 fit the screen in the width else hight.

I will check this in the computer if ok it push a update and let you know.

Thanks

**Comment by fgl27** [comment]
See if latest version of the app has any improve and let me know and see please.

I push a change using yours idea see above commit.

**Comment by xvasonix** [comment]
Thank you. Its much better but some spacing exist left and bottom.
Directly access webpage (https://fgl27.github.io/SmartTwitchTV/release/index.html) in web browser it shows perfect ratio.
But in app shows like this capture image. 
![Screenshot_2022-03-07-05-49-31-512](https://user-images.githubusercontent.com/94818711/156941911-32702960-2772-4fda-ba9b-c4326b73f5cb.jpeg)

**Comment by fgl27** [comment]
This is odd, I don't get way the app UI is offsetted to the right... that makes no sense to me...

As the screen is 16:10, the app must take all the width and have a small height, it is making it but something is pushing it to the right.

On that left side of the screen is there where the device has its on screen buttons? or the top bar (the one that shows wifi and etc icons)?

BTW I have change the app to center vertically 16:10 and bigger, close the app reopen and show me the result please.

If you know have a idea way the UI is be pushed to the right let me know.

**Comment by fgl27** [comment]
OK on the above the app is forced center on all direction maybe it help let me know/see the result.

**Comment by xvasonix** [comment]
It's Perfect!! Thank you!!!
![Uploading Screenshot_2022-03-07-08-14-47-009.jpeg…]()

**Comment by fgl27** [comment]
Nice enjoy! thank you!
