### ISSUE TITLE
Additional stream source support?

### ISSUE THREAD

**Issue by NormalBear** [fgl27/SmartTwitchTV#87]
More streamers are leaving twitch for facebook or youtube, moving the content around. It would be nice to be able to just throw in a youtube stream alongside the twitch streams. I know it's a whole separate API and everything and by no means an easy feature to implement, but just figured I'd throw the thought out there in case it wasn't already. I'm not sure there is even an alternative for multistreaming youtube on android.

**Comment by fgl27** [comment]
No this is a twitch so app only.
