### ISSUE TITLE
BTTV Emotes

### ISSUE THREAD

**Issue by BamboNo5** [fgl27/SmartTwitchTV#9]
BTTV Emotes don't seem to work anymore as of the latest update. FFZ Emotes work just fine. Running the App on an nvidia shieldTV (2017)
Would be nice if you know how to fix it :)

**Comment by fgl27** [comment]
Already fix this
https://github.com/fgl27/SmartTwitchTV/commit/9adf66d0c2d5e55c20ed6d040d84a89c2cb8b1df

close the app, holding return key after open all will be OK
