### ISSUE TITLE
Watch Party for next release

### ISSUE THREAD

**Issue by Bricio92** [fgl27/SmartTwitchTV#90]
hello, will you insert the watch Party function to be able to watch with our streamers in the next release? Thanks

**Comment by fgl27** [comment]
What do you mean?

What content you wanna to watch?

**Comment by Bricio92** [comment]
> What do you mean?
> 
> What content you wanna to watch?

I mean the watch party function. It's will be added with next release?

**Comment by fgl27** [comment]
I don't know what you wanna to watch.

Do nothing will be added.

**Comment by Bricio92** [comment]
> I don't know what you wanna to watch. Any twitch content ( live streams, VOD and clips) are already available.
> 
> So nothing will be added.

I mean the video party function. When I see a movie with the streamer.

**Comment by fgl27** [comment]
this is a twitch app it can' t access amazon prime video content.
