### ISSUE TITLE
ShutDown timer

### ISSUE THREAD

**Issue by talerzdebi** [fgl27/SmartTwitchTV#91]
**Is your feature request related to a problem? Please describe.**
Im using xiaomi mi stick but it doesn't shut down TV after 1h when im sleeping (no actions = TV OFF)
No idea why is it problem in this app or smth.

**Describe the solution you'd like**
Add shutdown timer to app if it is possible.

**Comment by fgl27** [comment]
There is already such feature.

![Screenshot_2021-12-30-09-01-29-50](https://user-images.githubusercontent.com/13755892/147750261-6f69a0a2-7db8-42ae-8224-2e65e9afe0bb.jpg)

**Comment by talerzdebi** [comment]
> There is already such feature. If disabled by default set the timer to enable.
> 
> ![Screenshot_2021-12-30-09-01-29-50](https://user-images.githubusercontent.com/13755892/147750261-6f69a0a2-7db8-42ae-8224-2e65e9afe0bb.jpg)

As i understand thats impossible to make turn off TV instead?

**Comment by fgl27** [comment]
No that allows the app to minimize on inactivity by a timer.

Then you need to enable the TV settings... Screen saver to: Turn screen of... And set the timer: when to start.

When all apps are minimized yours TV must turn off base on that timer.

**Comment by talerzdebi** [comment]
> No that allows the app to minimize on inactivity by a timer.
> 
> Then you need to enable the TV settings... Screen saver to: Turn screen off... And set the timer: when to start.
> 
> When all apps are minimized yours TV must turn off base on that timer.

Okay, ty for answer. one more thing just to dont make another issue.
Is it possible to download this apk on windows? Becuase on this app on my TV i dont have any ads, cant findy any adblock working on twitch so is it possible?
Or the only way is to use android emulator?
🤔🤔

**Comment by fgl27** [comment]
Yw, I'm not a Windows user, Windows 11 supposed to have native like support for Android APK, but I don't know what is the current state of it, you can just Google it.

You can download the APK from release
https://github.com/fgl27/SmartTwitchTV/releases

The app when downloaded from release will auto update so no need of a store like Play store.
