### ISSUE TITLE
Fire Stick 4k Max continues streaming after turned off via remote control

### ISSUE THREAD

**Issue by bradMatias** [fgl27/SmartTwitchTV#92]
I have a 1.2 TB data cap and I just hit it after 15 days of using this app.  I have used the Samsung version https://github.com/fgl27/smarttv-twitch for years and never once went over my data cap.  I think something is bugged here and this Android version is playing the stream in the background or something.  I am using a Fire Stick 4K Max which has multitasking support, so I'm thinking whenever I turn off the Fire stick without closing the app it might still be using data?  Any pointers on how I can start to debug this problem?

I have twitch on around 2-6 hours each day.
APK: 3.0.329
Device: Amazon - AFTKA Sdk: 28

**Comment by fgl27** [comment]
Are you sure you and you alone use that internet.

You need to play 24/7 a high bit rate stream to hit that in 15 days.

You probably have someone else using yours inherent to play 4k content or sunsetting like that 

Try to find s way to analisar yours network use that is the only way to debug it

**Comment by bradMatias** [comment]
the fire stick as traffic logging actually, so it told me the amount of data that specific app was using.  It says smart twitch used 1.53tb in a month.  I will try to test the traffic better today, but my first test was playing a stream then pressing the power key on my remote.  This puts the firestick into a sleep mode of some sort and then I waited 30min and turned it back on then checked the usage and saw it went from 1.53tb to 1.54tb

**Comment by fgl27** [comment]
10 Gb in 30 min isn't possible on any twitch stream... Any way maybe it was almost at 1.54.

I don't know how the sleep of that devices works, on my causes the app to stop all playback.

You can check the stream watching time on my device when I replicate yours steps, right after I put it to sleep the app stop when it wakes it restart the watching time goes back to zero.

Just exit the app before putting it to sleep by pressing the home button, also enable the settings option that auto minimized the app in inactivity.

![Screenshot_2022-01-16-15-49-56-89_8fb930a926872f0234df725c011c783b](https://user-images.githubusercontent.com/13755892/149673649-7691f0f7-33ae-4a5b-a8d7-49a2e57cc617.jpg)

**Comment by bradMatias** [comment]
something weird is happening with this Fire stick, somehow when I "turn it off" it's still using a great deal of data
![image](https://user-images.githubusercontent.com/3682725/149674653-53fc3e08-fbfc-495a-8543-218642ee0075.png)

if I exit out of smart twitch and then turn off the Fire stick I see no data usage, so I think somehow this device is not giving this app the right signal to tell smart twitch to stop playing
![image](https://user-images.githubusercontent.com/3682725/149674708-6755db6e-2bb4-41e9-956e-53d3844e11a0.png)

**Comment by bradMatias** [comment]
I called Amazon, they said there is nothing they can do.  If you turn off your TV the content will stream in the background unless you force close the app.  Same bug happens on youtube and netflix for example.  I do wonder though if there is anyway for this app to register for a hook on the Fire TV going into standby mode and stopping the stream?

**Comment by fgl27** [comment]
Maybe if the device sends screen on and off signal to apps.

Enable the inactivity feature in settings, the day I add implementations to check screen state I let you know.

**Comment by bradMatias** [comment]
Thanks, if I get the time I'd like to try to add a setting myself as a pull request that exits the app, or ends the stream if the screen state is off.  I tried using https://f-droid.org/en/packages/de.j4velin.wifiAutoOff/ and https://f-droid.org/packages/ryey.easer/ to turn off wifi when the screen is off, but I think they are not working for me.

**Comment by bradMatias** [comment]
In the meantime I found a solution, you can plug the Fire stick's USB power cord into the TV instead of the wall.  That way the device loses power when I power off my TV.  The big downside though is that now I need to wait around 15 seconds for the Fire stick to boot up, but it's better than paying $30 extra a month from my ISP because I exceed the data cap.


So I guess this issue should maybe be renamed as "Fire Stick 4k Max continues streaming after turned off via remote control" and the probable solution is there would need to be some way to check if the Fire Stick is in standby mode such as a screen off signal and setup a listener for that or something.

**Comment by NightHammer1000** [comment]
I also have a Samsung TV with the 4K Max and can not confirm this.
The Stick, the TV and even my AV Reciver all turn off once I hit the Power Button on the Fire TV Remote.
Just tested it. The Online Traffic on my 5G Router stops at once after I turn off.

Maybe check if HDMI CEC is working?

**Comment by fgl27** [comment]
I have added a screen off receiver on the app, it will stop the playback when detecting that the screen is off.

@bradMatias test app version 339 and let me know.

**Comment by fgl27** [comment]
Last version of the app add improves regarding preventing background playback.

check that .

close this do to inactivity.

**Comment by bradMatias** [comment]
Thanks for handling this sorry I forgot to test it, but I have moved my Fire Stick's power to use the TV's USB port as YouTube and Netflix also have this same bug, so I no longer feel it's worthwhile to power from the wall even if it saves time waiting for the stick to boot.
