### ISSUE TITLE
Unable to exit out of Chat Options.

### ISSUE THREAD

**Issue by hunter1749** [fgl27/SmartTwitchTV#93]
When I enter Options in Chat menu, I can't exit out.

**To Reproduce**
1. Go to someone's stream.
2. Click on the keyboard icon below for 'Chat menu'.
3. Once the menu appears, click on 'Options'.
4. Can't exit.

**Expected behavior**
When I press Return or exit, it should exit out of Options in Chat menu.
 
 **Device:**
Some TCL television.

**Comment by fgl27** [comment]
The app doesn't have an "'Chat menu", I don't know what you are doing show a image a picture as you may be lost it will help indentify where you are.

**Comment by hunter1749** [comment]
There is an icon like [this](https://www.pinclipart.com/picdir/middle/363-3632137_png-file-svg-keyboard-icon-png-clipart.png) at the bottom of the stream, below the pause and play button between other icons. When you click on it, you can send messages to chat. In that same menu, on the top left, there is a button Options. If you click on it, you can't exit it.

**Comment by fgl27** [comment]
Thank you will fix it and let you know

**Comment by fgl27** [comment]
Done thank you. :+1:
