### ISSUE TITLE
[ Twich API v5 Shutdown ] No streams, games, videos or related issue

### ISSUE THREAD

**Issue by G0mez82** [fgl27/SmartTwitchTV#94]
All of sudden app stopped showing any streams, videos and games. This happends on both, user menu and main menu. Reinstalled app and now it says user not found when trying to login. Only thing that was working before I reinstalled app was history and those streams was still able to be played.

Using Shield TV

**Comment by lilchina** [comment]
Working now

**Comment by fgl27** [comment]
Will leave this open add this is a recurring issue.

**Comment by fgl27** [comment]
Twitch is shutdown summer of they API read about it here

https://github.com/fgl27/SmartTwitchTV/blob/master/apk/TODO.md#migration-legacy-v5-to-new-twitch-api


Because of that is needed to update the app.

New API isn't one to one change, a lot charged or was removed, because of that there is lot work to be done.

I start charging here 

https://github.com/fgl27/SmartTwitchTV/commits/api_up

As I will probably not have the time to fix all before the deadline (next 28 of February) any help is needed to prevent the app from stop working.

**Comment by tgascoigne** [comment]
@fgl27 what would be the best way for people to help you migrate to the new API? are there particular endpoints or areas of the code that you'd like help with? I'd gladly spend some time on this to avoid it breaking on the 28th.

**Comment by AitoZ** [comment]
@fgl27 You might be able to snag some stuff from [Twire](https://github.com/twireapp/Twire) to get it done faster.

**Comment by fgl27** [comment]
> @fgl27 what would be the best way for people to help you migrate to the new API? are there particular endpoints or areas of the code that you'd like help with? I'd gladly spend some time on this to avoid it breaking on the 28th.

If you know how to code for the web you can let me know and I share some more detailed info on how to, the app has already a how to on the main readme https://github.com/fgl27/SmartTwitchTV#how-to-build-languages-and-etc-related


the most demanding changes are in the js part of the app, but there is also a java part.

If yo wanna try let me know.

Because I will only be able to address some changes before the month end.

**Comment by fgl27** [comment]
I will release a update version of the APK later today, and tomorrow I push some API changes.

Carefully read the changelog to know what changed

**Comment by fgl27** [comment]
I release the changes that migrate some parts of the app to the new API.

The content that has ben update is, General (none user) Live, Games and A Game Live, User specific Live included side panel.

Any new issues let me know.

**Comment by lilchina** [comment]
Did I miss something  I updated  got new token keys but twitch emotes list is empty

**Comment by fgl27** [comment]
> Did I miss something I updated got new token keys but twitch emotes list is empty

Twitch no longer provides API for that

**Comment by Belbs89** [comment]
Unable to see people who are live that I follow. Get a black screen and constant spinning circle? 

Have uninstalled and reinstalled to no luck. Other than that the app is all good and thank you for keeping this app alive ❤️👊

**Comment by fgl27** [comment]
> Unable to see people who are live that I follow. Get a black screen and constant spinning circle?
> 
> Have uninstalled and reinstalled to no luck. Other than that the app is all good and thank you for keeping this app alive heartfist_oncoming

That isn't a issue of the app 

Can you add a user and a authorization key?

They is all need to have access to followed content

**Comment by Belbs89** [comment]
Have added a user and key. When I go on User Menu then Live I just get a black screen and nothing loads. 

![image](https://user-images.githubusercontent.com/100086871/155162689-e042fb52-4f5f-4607-bf14-c1ebaf045bfd.jpg)

**Comment by fgl27** [comment]
You can control the app after that?

Show me the about off the app please.

**Comment by Belbs89** [comment]
Yeah it all works apart from that. 

![image](https://user-images.githubusercontent.com/100086871/155166133-32474caf-d153-4401-8d66-293cb333e23d.jpg)

**Comment by fgl27** [comment]
The side panel that shows live followed content works?

To open live followed on side panel press left on the side panel

**Comment by fgl27** [comment]
I see but the side panel you didn't try to open

See

![Screenshot_2022-02-22-12-52-09-51_8fb930a926872f0234df725c011c783b](https://user-images.githubusercontent.com/13755892/155169041-f3d8fea0-7dc6-4e3d-8b08-06f9dbc13146.jpg)

**Comment by Belbs89** [comment]
https://user-images.githubusercontent.com/100086871/155170387-cb56929e-4b7e-4a15-b1c0-d15d1a428538.MOV

**Comment by fgl27** [comment]
@Belbs89 
I believe there is an issue with your user, to check I need you to send me a file via email.

Navigate to this folder:

data/com.fgl27.twitch/Backup/

Grab the file user.json and send to me via email fglfgl27@gmail.com

Thanks for all the info once I manage to check yours user I let you know.

**Comment by Belbs89** [comment]
Email sent 👍

**Comment by Belbs89** [comment]
Decided to do a complete uninstall using ES file explorer. Done a fresh install from the play store and added key and now finally working 🙏👍 
![image](https://user-images.githubusercontent.com/100086871/155250727-042fe2dc-50f9-45ab-a62f-f0c6aa374b22.jpg)

**Comment by fgl27** [comment]
That maybe a false ok.

There maybe a stream causing the issue, it went off line so all ok...

If happens again let me know I test using the config you send me.

**Comment by O8server** [comment]
Recent update broke pretty much everything except watching streams. I can't search for channels, featured tab isn't working, but most importantly vods don't seem to load. This is what i see:![image](https://user-images.githubusercontent.com/87912493/155283414-de716711-f9cc-47ef-bebb-3dc985d037b5.jpeg) ![image](https://user-images.githubusercontent.com/87912493/155283446-3707bc57-ebd6-4fbd-be4c-9d1f5c0d54c3.jpeg)

**Comment by Sennat0r** [comment]
I can confirm this, live streams work with the latest update, games / videos / channels stopped working.

**Comment by fgl27** [comment]
Twitch is shutting down they API noting is brooking, takes time to update all if you don't like that update the app yourself this is an open project.

**Comment by Sennat0r** [comment]
No problem, just wanted to give some feedback. Unfortunately i'm no dev, so i can only help you with donations (which i did).

**Comment by fgl27** [comment]
> No problem, just wanted to give some feedback. Unfortunately i'm no dev, so i can only help you with donations (which i did). Thanks for your work!

Thank you I just don't wanna have a span of complaining, because if that happens we may get lost on what to fix.

**Comment by lilchina** [comment]
New bug for  me. When streamer is in follower only  mode I can not enter chat mode. I  am a follower.  If streamer  is not in follower only mode  I  can bring up chat box

**Comment by fgl27** [comment]
> New bug for me. When streamer is in follower only mode I can not enter chat mode. I am a follower. If streamer is not in follower only mode I can bring up chat box

Write to chat, depends on API b that was shutdown. When everything is migrated to a new API this will work.

**Comment by missiah** [comment]
Today I noticed it seems everything is dead in the User Menu except Live. The Searching, Games, Videos and Channels tab always show me this: https://imgur.com/a/UPT5K2e

Key is added successfully

I'm aware of the API changes and possible issues right now, just want to draw your attention to it if you not already aware of it. ❤️

**Comment by hunter1749** [comment]
> Today I noticed it seems everything is dead in the User Menu except Live. The Searching, Games, Videos and Channels tab always show me this: https://imgur.com/a/UPT5K2e
> 
> Key is added successfully
> 
> I'm aware of the API changes and possible issues right now, just want to draw your attention to it if you not already aware of it. ❤️
> 
> Thank you so much for the great App wouldn't know what to do without it.

Yeah only live streams seem to be working now, and clips. But no VODs or chatting.

**Comment by HelOWeen** [comment]
> Thank you I just don't wanna have a span of complaining, because if that happens we may get lost on what to fix.

Very understandable and totally acceptable.

This one is still much better than Twitch's own AndroidTV app, as _that_ one never had worked on my SmartTV _(Philips 49PUS7101)_ and only ever shows a black screen for every stream/VoD.

**Comment by Bricio92** [comment]
> Recent update broke pretty much everything except watching streams. I can't search for channels, featured tab isn't working, but most importantly vods don't seem to load. This is what i see:![image](https://user-images.githubusercontent.com/87912493/155283414-de716711-f9cc-47ef-bebb-3dc985d037b5.jpeg) ![image](https://user-images.githubusercontent.com/87912493/155283446-3707bc57-ebd6-4fbd-be4c-9d1f5c0d54c3.jpeg)

Do you have resolved this problem?

**Comment by hunter1749** [comment]
> > Recent update broke pretty much everything except watching streams. I can't search for channels, featured tab isn't working, but most importantly vods don't seem to load. This is what i see:![image](https://user-images.githubusercontent.com/87912493/155283414-de716711-f9cc-47ef-bebb-3dc985d037b5.jpeg) ![image](https://user-images.githubusercontent.com/87912493/155283446-3707bc57-ebd6-4fbd-be4c-9d1f5c0d54c3.jpeg)
> 
> Do you have resolved this problem?
It's still like that for me.

**Comment by Bricio92** [comment]
> > > Recent update broke pretty much everything except watching streams. I can't search for channels, featured tab isn't working, but most importantly vods don't seem to load. This is what i see:![image](https://user-images.githubusercontent.com/87912493/155283414-de716711-f9cc-47ef-bebb-3dc985d037b5.jpeg) ![image](https://user-images.githubusercontent.com/87912493/155283446-3707bc57-ebd6-4fbd-be4c-9d1f5c0d54c3.jpeg)
> > 
> > Do you have resolved this problem?
> 
> It's still like that for me.

you suggest to downgrade to the pprevious version to fix?

**Comment by hunter1749** [comment]
> > > > Recent update broke pretty much everything except watching streams. I can't search for channels, featured tab isn't working, but most importantly vods don't seem to load. This is what i see:![image](https://user-images.githubusercontent.com/87912493/155283414-de716711-f9cc-47ef-bebb-3dc985d037b5.jpeg) ![image](https://user-images.githubusercontent.com/87912493/155283446-3707bc57-ebd6-4fbd-be4c-9d1f5c0d54c3.jpeg)
> > > 
> > > 
> > > Do you have resolved this problem?
> > 
> > 
> > It's still like that for me.
> 
> you suggest to downgrade to the pprevious version to fix?

as @fgl27 already said, the api is the issue here, so downgrading most likely won't help, we just have to wait until twitch makes the new api work.

**Comment by henriklb** [comment]
I recently noticed that the streamer x going live notifications are not working anymore. Perhaps related to the API changes or?

**Comment by fgl27** [comment]
> I recently noticed that the "streamer is live" notifications are not working anymore. Perhaps related to the API changes or?

Everything not working is related to the API change.

**Comment by mtcuppers** [comment]
I understand that a lot of people are having trouble with the current state of the app, I've found a relatively reliable way to be able to watch pretty much any VOD.
Wait until your streamer is live, go to their stream and open the channel, go to the clips tab and open a clip from the VOD you want to watch. You can now press the "Open the broadcast" button through this clip and watch the entire VOD, this clip will be saved on your history tab so you now have a way to always have access to the streamer's channel even when they're not live. 
If advice like this is not allowed in here I apologize in advance.

**Comment by Akandesh** [comment]
I did some digging to see if I could help fix it and noticed that most ScreensObj_Init* functions need to use the helix api instead and because of that they need a header with the bearer authorization header and atm it's using Main_base_array_header header which is the wrong stuff and I think it should use Main_Bearer_Headers. I think some ScreenObj objects need some bool for which header to use but at this point I became uncomfortable with the code and don't want to contribute in a way that makes the code messy.

I'd like to know your thoughts on how you want this fixed @fgl27 :)

**Comment by Bricio92** [comment]
> I did some digging to see if I could help fix it and noticed that most ScreensObj_Init* functions need to use the helix api instead and because of that they need a header with the bearer authorization header and atm it's using Main_base_array_header header which is the wrong stuff and I think it should use Main_Bearer_Headers. I think some ScreenObj objects need some bool for which header to use but at this point I became uncomfortable with the code and don't want to contribute in a way that makes the code messy.
> 
> I'd like to know your thoughts on how you want this fixed @fgl27 :)

I'm very curious how and when it will fix this problem. maybe you could collaborate and help him.

**Comment by Bricio92** [comment]
> I did some digging to see if I could help fix it and noticed that most ScreensObj_Init* functions need to use the helix api instead and because of that they need a header with the bearer authorization header and atm it's using Main_base_array_header header which is the wrong stuff and I think it should use Main_Bearer_Headers. I think some ScreenObj objects need some bool for which header to use but at this point I became uncomfortable with the code and don't want to contribute in a way that makes the code messy.
> 
> I'd like to know your thoughts on how you want this fixed @fgl27 :)

I'm very curious how and when it will fix this problem. maybe you could collaborate and help him.

**Comment by fgl27** [comment]
I'm not here to be boss around thanks.

**Comment by catska2jc** [comment]
Anyone know if there is a way to directly input a VOD ID into the app? That way even with this vod directory not working due to the api change I could find a vod on PC and give it the direct link/video id to play

**Comment by fgl27** [comment]
I finished the app update.

Some screen are no longer supported:

1. User VOD.
2. Top VOD.
3. Top Clip.
4. Search Live.

Some screen behavior changed, nothing can be done today as simply this new twitch API sucks.

If things change on the future or I manage to find some replacements I will add back some removed screen and improve the app.

**Comment by NightHammer1000** [comment]
Thanks for the Great work. The Missing VOD Screen sucks a bit because it was litterly the best thing about this app. Hope you find a way to add it back.

**Comment by hunter1749** [comment]
What are the limitations to the followed games? I saw it mentioned in change log, but I don't quite understand.

**Comment by fgl27** [comment]
> What are the limitations to the followed games? I saw it mentioned in change log, but I don't quite understand.

What you don't understand?

It's undocumented API that is limited to return 100 live games. If you follow to many games and they are all live some will not show. The one that do not show is the one you follow last.

An live game is a game that there anyone streaming it.

**Comment by catska2jc** [comment]
Thanks for the fix for the new API! Works great now

**Comment by fgl27** [comment]
Channels on the home screen and notifications are now working.

If anyone has a new issue open a new one.
