### ISSUE TITLE
Connection failed, unable to load content. Hit refresh to try again

### ISSUE THREAD

**Issue by YMZ1903** [fgl27/SmartTwitchTV#95]
Hi, 
I am using the app on a daily basis, but unfortunately I got now following message wherever I navigate.

`Connection failed, unable to load content. Hit refresh to try again`

It is also reproducible on another Samsung TV.

I guess some hosting server is down? 
Thank you in advance!

**Comment by Juanjor3** [comment]
Hi, same here.

**Comment by YMZ1903** [comment]
It is working again, as I thought maybe a downtime. 
And again, thank you for the great app!
